# **Choosing Appropriate Encoding for Variables and Creating Hybrid Matrix for Model Input:**

In [301]:
import pandas as pd
import numpy as np
#import skfuzzy as fuzz  
import matplotlib.pyplot as plt
import seaborn as sns

In [302]:
df= pd.read_csv("C:\\Users\\MyMachine\\Desktop\\Fuzzy-Logic-Based-Maternal-Mental-Health-Risk-Assessment\\Data_Synthesis\\sampled_maternal_data_20k.csv")

In [303]:
df.shape

(20000, 32)

In [304]:
df.columns

Index(['age', 'residence', 'province', 'ethnicity',
       'caste_discrimination_exposure', 'education_level', 'occupation',
       'family_type', 'wealth_index', 'monthly_household_income',
       'food_security', 'housing_quality', 'financial_stress_level', 'parity',
       'anc_visits', 'delivery_type', 'birth_complications',
       'baby_health_status', 'gestational_age', 'maternal_age_at_first_birth',
       'previous_pregnancy_loss', 'partner_support_score',
       'family_support_score', 'domestic_violence_exposure',
       'social_isolation_score', 'sleep_quality', 'stressful_life_events',
       'mental_health_awareness', 'distance_to_health_facility',
       'health_insurance', 'previous_mental_health_consultation',
       'ppd_risk_level'],
      dtype='object')

In [305]:
df.select_dtypes(include=[np.number]).columns

Index(['age', 'monthly_household_income', 'housing_quality',
       'financial_stress_level', 'parity', 'anc_visits', 'gestational_age',
       'maternal_age_at_first_birth', 'partner_support_score',
       'family_support_score', 'social_isolation_score', 'sleep_quality',
       'stressful_life_events', 'distance_to_health_facility'],
      dtype='object')

In [265]:
df.select_dtypes(include= "object").head(1)

,residence,province,ethnicity,caste_discrimination_exposure,education_level,occupation,family_type,wealth_index,food_security,delivery_type,birth_complications,baby_health_status,previous_pregnancy_loss,domestic_violence_exposure,mental_health_awareness,health_insurance,previous_mental_health_consultation,ppd_risk_level
0,Urban,Koshi,Hill High Caste,No,Secondary,Sales/Service,Nuclear,Richer,Secure,Cesarean,No,Healthy,No,Rarely,Medium,Yes,Yes,No/Minimal Risk

In [306]:
df.select_dtypes(include= "object").columns

Index(['residence', 'province', 'ethnicity', 'caste_discrimination_exposure',
       'education_level', 'occupation', 'family_type', 'wealth_index',
       'food_security', 'delivery_type', 'birth_complications',
       'baby_health_status', 'previous_pregnancy_loss',
       'domestic_violence_exposure', 'mental_health_awareness',
       'health_insurance', 'previous_mental_health_consultation',
       'ppd_risk_level'],
      dtype='object')

-----
-----
-----

### **1. age (int64)**

* Age is numeric, continuous, and fuzzy ranges like *young, middle-aged, older* make sense for maternal health risk assessment.

* **Action:** Fuzzify.

In [267]:
df["age"].describe()

count    20000.000000
mean        29.975450
std          8.348696
min         16.000000
25%         23.000000
50%         30.000000
75%         37.000000
max         44.000000
Name: age, dtype: float64

### **2. residence (object)**

* Nominal (e.g., Urban/Rural) with no inherent order. Fuzzy membership doesn’t add interpretability.

* **Best option:** Binary or One-Hot Encode.

In [268]:
df["residence"].value_counts()

residence
Rural    12591
Urban     7409
Name: count, dtype: int64

### **3. province (object)**

* Nominal geographic categories; fuzzy logic doesn’t help.

* **Best option:** One-Hot Encode.

In [269]:
df["province"].value_counts()

province
Bagmati          3567
Koshi            3200
Lumbini          3022
Madhesh          2947
Karnali          2463
Sudurpashchim    2444
Gandaki          2357
Name: count, dtype: int64

### **4. ethnicity (object)**

* Nominal, no order.

* **Best option:** One-Hot Encode.

In [270]:
df["ethnicity"].value_counts()

ethnicity
Hill High Caste    7534
Dalit              4304
Janajati           3688
Terai Caste        3503
Muslim              971
Name: count, dtype: int64

### **5. caste_discrimination_exposure (object)**

* Binary (Yes/No); fuzzifying is unnecessary.

* **Best option:** Label Encode (0/1) or Binary Encode (0/1).

In [271]:
df["caste_discrimination_exposure"].value_counts()

caste_discrimination_exposure
No     17615
Yes     2385
Name: count, dtype: int64


```python
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['caste_discrimination_exposure'] = le.fit_transform(df['caste_discrimination_exposure'])
```

### **6. education_level (object):**

* Ordinal (No schooling < Primary < Secondary < Higher); can define fuzzy sets like *low, medium, high education*.

* Fuzzify.

In [272]:
df["education_level"].value_counts()

education_level
Secondary       10099
Primary          3919
No education     3032
Higher           2950
Name: count, dtype: int64

### **7. occupation (object)**

* Nominal; no logical fuzzy ordering.

* One-Hot Encode.

In [273]:
df["occupation"].value_counts()

occupation
Agriculture                          8649
Sales/Service                        3848
Manual                               3293
Professional/Technical/Managerial    2815
Clerical                             1395
Name: count, dtype: int64

### **8. family_type (object):**

* Nominal (e.g., nuclear/joint).

* Label / Binary Encoding (0–1)

In [274]:
df["family_type"].value_counts()

family_type
Nuclear           13098
Joint/Extended     6902
Name: count, dtype: int64

### **9. wealth_index (object)**

* Ordinal (Poorest → Richest); fuzzy ranges like *low, medium, high wealth* are meaningful.

* Fuzzify.

- We should not apply traditional scaling or transformation before fuzzification. We should encode the ordinal order and then apply fuzzy membership functions directly because traditional scaling destroys semantic meaning.

- First transformed using ordinal encoding to preserve its rank order and subsequently directly fuzzified into low, medium, and high wealth membership functions.

In [275]:
df["wealth_index"].value_counts()

wealth_index
Poorest    4506
Middle     4339
Poorer     3898
Richer     3893
Richest    3364
Name: count, dtype: int64

### **10. monthly_household_income (int64)**

* Continuous numeric variable; can define fuzzy ranges (low, medium, high income).

* Fuzzify.

In [276]:
df["monthly_household_income"].describe()

count     20000.000000
mean      45830.999300
std       39026.142782
min        8000.000000
25%       18000.000000
50%       31644.500000
75%       59835.250000
max      180000.000000
Name: monthly_household_income, dtype: float64

### **11. food_security (object):**

* Ordinal (e.g., Insecure < Marginal < Secure); fuzzy sets make sense.

* Fuzzify.

In [277]:
df["food_security"].value_counts()

food_security
Secure                 8840
Mildly insecure        4605
Moderately insecure    3390
Severely insecure      3165
Name: count, dtype: int64

### **12. housing_quality (int64)**

* Numeric/ordinal; fuzzy sets like *poor, average, good* can be defined.

* Fuzzify.

In [278]:
df["housing_quality"].describe()

count    20000.000000
mean         5.582200
std          2.042878
min          1.000000
25%          4.000000
50%          6.000000
75%          7.000000
max         10.000000
Name: housing_quality, dtype: float64

### **13. financial_stress_level (int64)**

* Numeric/ordinal; fuzzy sets like *low, medium, high stress* are interpretable.

* Fuzzify.

In [279]:
df["financial_stress_level"].value_counts()

financial_stress_level
6     2296
7     2233
5     2208
8     1990
4     1989
0     1769
3     1765
2     1706
9     1386
10    1353
1     1305
Name: count, dtype: int64

In [280]:
df["financial_stress_level"].describe()

count    20000.00000
mean         5.01695
std          2.95508
min          0.00000
25%          3.00000
50%          5.00000
75%          7.00000
max         10.00000
Name: financial_stress_level, dtype: float64

### **14. parity (int64)**

* Numeric, discrete; fuzzy sets like *low, medium, high parity* make sense.

* Fuzzify.

In [281]:
df["parity"].describe()

count    20000.000000
mean         1.630050
std          1.461093
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          8.000000
Name: parity, dtype: float64

### **15. anc_visits (int64)**

* Numeric; fuzzy ranges for *low, adequate, high* prenatal care can be defined.

* Fuzzify.

In [282]:
df["anc_visits"].describe()

count    20000.000000
mean         5.497250
std          2.422042
min          0.000000
25%          4.000000
50%          6.000000
75%          7.000000
max         12.000000
Name: anc_visits, dtype: float64

### **16. delivery_type (object)**

* Nominal (e.g., Normal/C-section); fuzzy ranges don’t add value.

* One-Hot Encode.

In [283]:
df["delivery_type"].value_counts()

delivery_type
Normal      14582
Cesarean     4511
Assisted      907
Name: count, dtype: int64

### **17. birth_complications (object)**

* Binary/nominal; fuzzification unnecessary.

* Label Encode/ Binary Encode

In [284]:
df["birth_complications"].value_counts()

birth_complications
No     15224
Yes     4776
Name: count, dtype: int64

### **18. baby_health_status (object)**

* Nominal (e.g., healthy/sick); fuzzy sets unlikely to improve interpretability.

* One-Hot Encode.

In [285]:
df["baby_health_status"].value_counts()

baby_health_status
Healthy         16588
Minor issues     2515
Major issues      897
Name: count, dtype: int64

### **19. gestational_age (int64)**

* Continuous numeric; fuzzy ranges like *preterm, term, post-term* are meaningful.

* Fuzzify.

In [286]:
df["gestational_age"].describe()

count    20000.000000
mean        38.489000
std          2.265598
min         29.000000
25%         37.000000
50%         39.000000
75%         40.000000
max         42.000000
Name: gestational_age, dtype: float64

### **20. maternal_age_at_first_birth (int64)**

* Numeric; fuzzy ranges like *teenage, adult, mature* make sense.

* Fuzzify.

In [287]:
df["maternal_age_at_first_birth"].describe()

count    20000.000000
mean        21.566200
std          4.697619
min         15.000000
25%         19.000000
50%         21.000000
75%         23.000000
max         44.000000
Name: maternal_age_at_first_birth, dtype: float64

### **21. previous_pregnancy_loss (object)**

* **Why not fuzzifiable:** Binary (Yes/No); fuzzification unnecessary.

* Label Encode/ Binary Encode

In [288]:
df["previous_pregnancy_loss"].value_counts()

previous_pregnancy_loss
No     16556
Yes     3444
Name: count, dtype: int64

### **22. partner_support_score (float64):**

* Continuous; fuzzy ranges like *low, medium, high support* are interpretable.

* Fuzzify.

In [289]:
df["partner_support_score"].describe()

count    20000.000000
mean         6.593150
std          2.115375
min          0.000000
25%          5.100000
50%          6.700000
75%          8.200000
max         10.000000
Name: partner_support_score, dtype: float64

### **23. family_support_score (float64):**

* Continuous; fuzzy ranges like *low, medium, high support* are interpretable.

* Fuzzify

In [290]:
df["family_support_score"].describe()

count    20000.000000
mean         6.209595
std          2.220976
min          0.000000
25%          4.600000
50%          6.200000
75%          7.800000
max         10.000000
Name: family_support_score, dtype: float64

### **24. domestic_violence_exposure (object)**

* The domestic violence exposure variable represents an ordered frequency-based psychosocial construct (Never–Often). Therefore, instead of using crisp categorical encoding, it was directly modeled using fuzzy membership functions, allowing gradual transitions between low, moderate, and high exposure levels. This approach better captures the continuous nature of psychological stress and its impact on postpartum depression risk.

* fuzzify.

- > `Never < Rarely < Sometimes < Often`

```py
        Low Exposure → Never + Rarely
        Medium Exposure → Rarely + Sometimes
        High Exposure → Sometimes + Often

        Using:
        Triangular or trapezoidal membership functions
        With overlapping regions
        No traditional scaling is required.
```

In [291]:
df["domestic_violence_exposure"].value_counts()

domestic_violence_exposure
Never        12696
Rarely        3613
Sometimes     2745
Often          946
Name: count, dtype: int64

### **25. social_isolation_score (float64)**

* Continuous; fuzzy ranges like *low, medium, high isolation* are meaningful.

* Fuzzify.

In [292]:
df["social_isolation_score"].describe()

count    20000.000000
mean         4.569215
std          2.130144
min          0.000000
25%          3.000000
50%          4.400000
75%          6.000000
max         10.000000
Name: social_isolation_score, dtype: float64

### **26. sleep_quality (float64)**

* Continuous; fuzzy ranges like *poor, average, good* are meaningful.

* Fuzzify.

In [293]:
df["sleep_quality"].describe()

count    20000.000000
mean         6.659985
std          1.691710
min          1.000000
25%          5.500000
50%          6.700000
75%          7.900000
max         10.000000
Name: sleep_quality, dtype: float64

### **27. stressful_life_events (int64)**

* Discrete numeric; fuzzy ranges like *low, medium, high stress events* are meaningful.

* Fuzzify.

In [294]:
df["stressful_life_events"].describe()

count    20000.000000
mean         1.083450
std          1.074916
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          5.000000
Name: stressful_life_events, dtype: float64

### **28. mental_health_awareness (object):**

* Nominal; fuzzy sets don’t add value.

* One-Hot Encode.

In [295]:
df["mental_health_awareness"].value_counts()

mental_health_awareness
Medium    11735
Low        4788
High       3477
Name: count, dtype: int64

### **29. distance_to_health_facility (float64)**

* Continuous; fuzzy ranges like *near, moderate, far* make sense.

* Fuzzify.

In [296]:
df["distance_to_health_facility"].describe()

count    20000.000000
mean         4.606329
std          5.815983
min          0.500000
25%          1.200000
50%          2.620000
75%          5.630000
max         50.000000
Name: distance_to_health_facility, dtype: float64

### **30. health_insurance (object)**

* Nominal/binary; fuzzification unnecessary.

* Label / Binary.

In [297]:
df["health_insurance"].value_counts()

health_insurance
No     14335
Yes     5665
Name: count, dtype: int64

### **31. previous_mental_health_consultation (object)**

* Binary; fuzzification unnecessary.

* Label Encode.

In [298]:
df["previous_mental_health_consultation"].value_counts()

previous_mental_health_consultation
No     18855
Yes     1145
Name: count, dtype: int64

### **32. ppd_risk_level (object) – Target**

* Already categorical; it’s the **`label`**, not a feature.

* Label Encode for classification.

- The target variable ppd_risk_level represents ordered clinical severity categories (no/minimal, possible, and probable depression). Therefore, it was transformed using ordinal label encoding (0–2) to preserve the inherent severity ranking and to support ordinal classification and fuzzy defuzzification.

**Why Target Encoding is INVALID for a Target Variable:**
   - Uses the target to encode itself
   - Creates data leakage   
   - Is mathematically meaningless for labels

In [299]:
df["ppd_risk_level"].value_counts()

ppd_risk_level
No/Minimal Risk        8149
Possible Depression    8092
Probable Depression    3759
Name: count, dtype: int64

-----
----

## **Crisp Feature Engineering:**

In [307]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

**One-Hot Encoding Features:**

In [308]:
onehot_features = [
    'province',
    'ethnicity',
    'occupation',
    'delivery_type',
    'baby_health_status',
    'mental_health_awareness'
]

**Binary / Label Encoded Features:**

In [309]:
binary_features = [
    'residence',
    'caste_discrimination_exposure',
    'family_type',
    'birth_complications',
    'previous_pregnancy_loss',
    'health_insurance',
    'previous_mental_health_consultation'
]

**Ordinal Encoded Target:**

In [310]:
target_feature = 'ppd_risk_level'

ppd_order = [['No/Minimal Risk', 'Possible Depression', 'Probable Depression']]

**One-Hot Encode Nominal Features:**

In [311]:
onehot_features

['province',
 'ethnicity',
 'occupation',
 'delivery_type',
 'baby_health_status',
 'mental_health_awareness']

In [312]:
df["province"].unique()

array(['Koshi', 'Madhesh', 'Sudurpashchim', 'Gandaki', 'Lumbini',
       'Bagmati', 'Karnali'], dtype=object)

In [313]:
onehot_encoder = OneHotEncoder(sparse_output=False, drop='first')

onehot_encoded_array = onehot_encoder.fit_transform(df[onehot_features])

onehot_encoded_df = pd.DataFrame(
    onehot_encoded_array,
    columns=onehot_encoder.get_feature_names_out(onehot_features),
    index=df.index
)

In [314]:
onehot_encoded_df

,province_Gandaki,province_Karnali,province_Koshi,province_Lumbini,province_Madhesh,province_Sudurpashchim,ethnicity_Hill High Caste,ethnicity_Janajati,ethnicity_Muslim,ethnicity_Terai Caste,occupation_Clerical,occupation_Manual,occupation_Professional/Technical/Managerial,occupation_Sales/Service,delivery_type_Cesarean,delivery_type_Normal,baby_health_status_Major issues,baby_health_status_Minor issues,mental_health_awareness_Low,mental_health_awareness_Medium
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
19996,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
19997,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
19998,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
19999,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

**Binary / Label Encode Dichotomous Features:**

In [315]:
df_binary_encoded = df[binary_features].copy()
df_binary_encoded

,residence,caste_discrimination_exposure,family_type,birth_complications,previous_pregnancy_loss,health_insurance,previous_mental_health_consultation
0,Urban,No,Nuclear,No,No,Yes,Yes
1,Rural,Yes,Nuclear,Yes,No,No,No
2,Rural,No,Nuclear,No,No,No,No
3,Rural,No,Joint/Extended,No,No,No,No
4,Rural,No,Nuclear,No,No,No,No
...,...,...,...,...,...,...,...
19995,Rural,No,Joint/Extended,No,Yes,No,No
19996,Urban,No,Nuclear,No,No,Yes,No
19997,Urban,No,Nuclear,No,Yes,No,No
19998,Rural,No,Joint/Extended,No,No,No,No
19999,Rural,No,Nuclear,No,No,No,No

In [316]:
label_encoders = {}

for col in binary_features:
    le = LabelEncoder()
    df_binary_encoded[col] = le.fit_transform(df_binary_encoded[col])
    label_encoders[col] = le

In [204]:
label_encoders

{'residence': LabelEncoder(),
 'caste_discrimination_exposure': LabelEncoder(),
 'family_type': LabelEncoder(),
 'birth_complications': LabelEncoder(),
 'previous_pregnancy_loss': LabelEncoder(),
 'health_insurance': LabelEncoder(),
 'previous_mental_health_consultation': LabelEncoder()}

In [317]:
df_binary_encoded

,residence,caste_discrimination_exposure,family_type,birth_complications,previous_pregnancy_loss,health_insurance,previous_mental_health_consultation
0,1,0,1,0,0,1,1
1,0,1,1,1,0,0,0
2,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...
19995,0,0,0,0,1,0,0
19996,1,0,1,0,0,1,0
19997,1,0,1,0,1,0,0
19998,0,0,0,0,0,0,0
19999,0,0,1,0,0,0,0

In [318]:
df_binary_encoded.shape

(20000, 7)

**Ordinal Encode the Target Variable:**

In [319]:
ordinal_encoder = OrdinalEncoder(categories=ppd_order)

df_target_encoded = pd.DataFrame(
    ordinal_encoder.fit_transform(df[[target_feature]]).astype(int),
    columns=[target_feature],
    index=df.index
)

In [320]:
df_target_encoded

       ppd_risk_level
0                   0
1                   2
2                   0
3                   0
4                   1
...               ...
19995               0
19996               0
19997               0
19998               1
19999               0

[20000 rows x 1 columns]

In [443]:
# Get the mapping of the target feature ppd_risk_level 

ppd_risk_mapping = {level: code for code, level in enumerate(df['ppd_risk_level'].unique())}
print(ppd_risk_mapping)

# Apply the mapping to the target feature
df['ppd_risk_level'] = df['ppd_risk_level'].map(ppd_risk_mapping)

{'No/Minimal Risk': 0, 'Probable Depression': 1, 'Possible Depression': 2}

This dataframe now contains **only non-fuzzy encoded features**:

In [321]:
df_crisp_encoded = pd.concat(
    [onehot_encoded_df, df_binary_encoded, df_target_encoded],
    axis=1
)

In [322]:
df_crisp_encoded.head(3)

,province_Gandaki,province_Karnali,province_Koshi,province_Lumbini,province_Madhesh,province_Sudurpashchim,ethnicity_Hill High Caste,ethnicity_Janajati,ethnicity_Muslim,ethnicity_Terai Caste,...,mental_health_awareness_Low,mental_health_awareness_Medium,residence,caste_discrimination_exposure,family_type,birth_complications,previous_pregnancy_loss,health_insurance,previous_mental_health_consultation,ppd_risk_level
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1,0,1,0,0,1,1,0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0,1,1,1,0,0,0,2
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0,0,1,0,0,0,0,0

> Nominal categorical variables (province, ethnicity, occupation, delivery type, baby health status, and mental health awareness) were transformed using **one-hot encoding**. Dichotomous predictors (residence, caste discrimination exposure, family type, birth complications, previous pregnancy loss, health insurance, and previous mental health consultation) were encoded using **binary label encoding (0–1)**. The target variable *ppd_risk_level*, representing ordered clinical severity, was transformed using **ordinal encoding (0–2)**. These crisp-transformed features were later concatenated with fuzzified continuous and ordinal predictors to construct the final hybrid fuzzy–crisp feature matrix.

**Notes:** 
- Do not scale any of these one-hot encoded or binary features.
- Do not fuzzify any of the encoded features.
- Only the continuous / ordinal psychological and clinical variables go into the fuzzy pipeline.

#### **Creating a Pipeline:**

In [ ]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, FunctionTransformer
from sklearn.base import BaseEstimator, TransformerMixin

# Define the features and the target as in the prompt
onehot_features = [
    'province',
    'ethnicity',
    'occupation',
    'delivery_type',
    'baby_health_status',
    'mental_health_awareness'
]

binary_features = [
    'residence',
    'caste_discrimination_exposure',
    'family_type',
    'birth_complications',
    'previous_pregnancy_loss',
    'health_insurance',
    'previous_mental_health_consultation'
]

target_feature = 'ppd_risk_level'
ppd_order = [['No/Minimal Risk', 'Possible Depression', 'Probable Depression']]

# 1. Pipeline for One-Hot Encoding
onehot_pipeline = Pipeline([
    ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first'))
])

# 2. Pipeline for Binary/Label Encoding
# For binary features, OrdinalEncoder without categories will work like LabelEncoder
# for 0/1 encoding if the input is only two unique string values.
binary_pipeline = Pipeline([
    ('label', OrdinalEncoder()) # This achieves similar 0/1 encoding as LabelEncoder for binary features
])

# 3. Combine One-Hot and Binary pipelines using ColumnTransformer
# The remainder='passthrough' is often useful for non-categorical columns, but here
# we explicitly specify all categorical/binary columns.
crisp_feature_preprocessing = ColumnTransformer(
    transformers=[
        ('onehot_enc', onehot_pipeline, onehot_features),
        ('binary_enc', binary_pipeline, binary_features)
    ],
    # Important: Setting remainder='drop' ensures only the transformed columns are outputted
    remainder='drop',
    verbose_feature_names_out=False
)

# 4. Final 'Crisp' Feature Pipeline (excluding the target feature transformation)
crisp_feature_pipeline = Pipeline(steps=[
    ('crisp_features', crisp_feature_preprocessing)
])

print("Crisp Feature Pipeline created successfully.")
print(crisp_feature_pipeline)

----
----
-----
-----

## **Fuzzification:**

#### **1. Age:**

In [323]:
df["age"].describe()

count    20000.000000
mean        29.975450
std          8.348696
min         16.000000
25%         23.000000
50%         30.000000
75%         37.000000
max         44.000000
Name: age, dtype: float64

The `'age'` feature ranges from $\mathbf{16}$ to $\mathbf{44}$ years, with a median of $\mathbf{30}$. We will redefine the fuzzy sets to reflect the broader distribution while keeping the core risk profiles aligned with maternal mental health literature.

**Membership Functions and Shapes:**

We will maintain the use of **Trapezoidal** and **Triangular** membership functions for their clarity and computational efficiency.

  * **Young Mother (Risk/Vulnerability):** Extended down to 16. Full membership is assigned to the early risk years (e.g., up to 22). This group is highly vulnerable to PPD due to resource constraints and psychological immaturity.
  
  * **Prime Motherhood (Reference/Low Risk):** The central, most populous range (24-36), centered around the median/mean.
  
  * **Advanced Maternal Age (Potential Risk/Attention):** Starts the slope before 35 and extends to 44, encompassing the 'advanced' category recognized in obstetrics, which may be associated with increased stress.

We will use three overlapping fuzzy sets: **Young Mother**, **Prime Motherhood**, and **Advanced Maternal Age**.

**Fuzzy Sets and Ranges:**

| Fuzzy Set (Linguistic Term) | Range of Age (Approximate Support) | Description and Rationale |
| :-------------------------- | :---------------------------------- | :----------------------------------------------------------------------------------------------------------------------------------- |
| **Young Mother** | $16 - 26$                           | Captures the beginning of the mother-age demographic (min 16). Full membership up to the early twenties. |
| **Prime Motherhood** | $24 - 36$                           | The central cohort, centered on the median age of 30. Reference group for typical risk factors. |
| **Advanced Maternal Age** | $34 - 44$                           | Reflects the clinical $\geq 35$ category, extending to the maximum age of 44 to capture increasing age-related risks and stresses. |

**Detailed Fuzzy Set Definition:**

A. Fuzzy Set: **Young Mother**

  * **Description:** Mothers at the high-risk, early stages of childbearing. Membership reflects maximum risk at the start of the observed population (16 years).

  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Mathematical Formula:**
    > $$\mu_{\text{Young}}(x) = \text{trapmf}(x; 16, 16, 22, 26)$$
    > $$\mu_{\text{Young}}(x) = \begin{cases} 1 & \text{if } x \le 22 \\ \frac{26-x}{26-22} & \text{if } 22 < x < 26 \\ 0 & \text{if } x \ge 26 \end{cases}$$
  
  * **Shape:** **Left-sloping ramp**. Full membership ($\mu=1$) from 16 to 22 (Core), linearly decreasing to $0$ at 26 (Support End).
  
  * **ASCII Representation:**
    ```py 
          1 |-----|
            |     \
            |      \
            |       \
        0 --+--------\------
          16 22      26
    ```

| Parameter | Value | Location on the Curve |
| :-------- | :---- | :--------------------------------------------- |
| $a$       | 16    | Lower limit of full membership (min age) |
| $b$       | 16    | Upper limit of full membership (start of slope) |
| $c$       | 22    | Start of the descent slope (Core) |
| $d$       | 26    | End of the descent slope (Support End) |


B. Fuzzy Set: **Prime Motherhood:**

  * **Description:** The reference population, centered around the median age of 30. This group is the most numerous and represents the typical PPD risk profile.
  
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  
  * **Mathematical Formula:**
    > $$\mu_{\text{Prime}}(x) = \text{trimf}(x; 24, 30, 36)$$
    > $$\mu_{\text{Prime}}(x) = \begin{cases} 0 & \text{if } x \le 24 \text{ or } x \ge 36 \\ \frac{x-24}{30-24} & \text{if } 24 < x \le 30 \\ \frac{36-x}{36-30} & \text{if } 30 < x < 36 \end{cases}$$
  
  * **Shape:** **Symmetrical Triangle**. Membership rises from $0$ at $24$ to a peak of $1$ at $30$ (median/mean), and falls back to $0$ at $36$.
  
  * **ASCII Representation:**
    ```py 
          1 |      / \
            |     /   \
            |    /     \
            |   /       \
        0 --+--/---------\---
          16 24 30       36
    ```
| Parameter | Value | Location on the Curve |
| :-------- | :---- | :------------------------------------- |
| $a$       | 24    | Left foot (Support Start)              |
| $b$       | 30    | Peak/Apex (Full Membership Core)       |
| $c$       | 36    | Right foot (Support End)               |

C. Fuzzy Set: **Advanced Maternal Age**

  * **Description:** Mothers at or past the clinical threshold of 35, where the risk profile may include higher stress due to biological and social expectations. Membership is maximized at the upper bound of the sample (44 years).
  
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Mathematical Formula:**
    > $$\mu_{\text{Advanced}}(x) = \text{trapmf}(x; 34, 40, 44, 44)$$
    > $$\mu_{\text{Advanced}}(x) = \begin{cases} 0 & \text{if } x \le 34 \\ \frac{x-34}{40-34} & \text{if } 34 < x < 40 \\ 1 & \text{if } x \ge 40 \end{cases}$$
  
  * **Shape:** **Right-sloping ramp**. Membership is $0$ at $34$ (Support Start), rises linearly to $1$ at $40$ (Core), and remains $1$ up to 44 (max age).
  
  * **ASCII Representation:**
    ```py 
          1 |          |------|
            |         /|
            |        / |
            |       /  |
        0 --+------/---|------
          16 34  40 44
    ```

| Parameter | Value | Location on the Curve |
| :-------- | :---- | :--------------------------------------------- |
| $a$       | 34    | Start of the ascent slope (Support Start)      |
| $b$       | 40    | End of the ascent slope (Core)                 |
| $c$       | 44    | Lower limit of full membership (max age) |
| $d$       | 44    | Upper limit of full membership (max age) |

In [324]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

In [325]:
# Define  parameters for each fuzzy set 

# A. Young Mother (Left-Open Trapezoidal: [16, 16, 22, 28])
young_mother_params = [16, 16, 22, 28]

# B. Prime Motherhood (Triangular: [26, 30, 38])
prime_mother_params = [26, 30, 38]
 
# C. Advanced Maternal Age (Right-Open Trapezoidal: [36, 40, 44, 44])
advanced_age_params = [36, 40, 44, 44]

In [326]:
# Fuzzification Function (Applied to the entire column) ---

def apply_fuzzy_membership_with_overlap(age_series: pd.Series) -> pd.DataFrame:
    """
    Calculates the degree of membership for the entire 'age' column using the 
    revised, wider-overlapping fuzzy sets.
    """
    
    # Define the universe of discourse (16 to 44)
    age_universe = np.arange(16, 45, 1)

    # Compute the membership functions (MFs) across the defined universe
    young_mother_mf = fuzz.trapmf(age_universe, young_mother_params)
    prime_mother_mf = fuzz.trimf(age_universe, prime_mother_params)
    advanced_age_mf = fuzz.trapmf(age_universe, advanced_age_params)

    # Apply interpolation to the entire age column
    
    # Calculate membership for 'Young Mother'
    mu_young = [
        fuzz.interp_membership(age_universe, young_mother_mf, x)
        for x in age_series
    ]
    
    # Calculate membership for 'Prime Motherhood'
    mu_prime = [
        fuzz.interp_membership(age_universe, prime_mother_mf, x)
        for x in age_series
    ]
    
    # Calculate membership for 'Advanced Maternal Age'
    mu_advanced = [
        fuzz.interp_membership(age_universe, advanced_age_mf, x)
        for x in age_series
    ]
    
    # 3. Create the new fuzzy feature DataFrame
    fuzzy_features_df = pd.DataFrame({
        'mu_age_young': mu_young,
        'mu_age_prime': mu_prime,
        'mu_age_advanced': mu_advanced
    })
    
    return fuzzy_features_df

In [327]:
# Execute Fuzzification and Merge

fuzzy_df = apply_fuzzy_membership_with_overlap(df['age'])

In [328]:
df.shape

(20000, 32)

In [ ]:
#df = pd.concat([df, fuzzy_df], axis=1)

In [330]:
fuzzy_df.sample(10)

       mu_age_young  mu_age_prime  mu_age_advanced
9583       0.000000         0.000             1.00
15201      0.000000         0.000             1.00
15543      0.000000         1.000             0.00
18035      0.833333         0.000             0.00
1843       0.000000         0.000             1.00
18000      0.500000         0.000             0.00
8393       0.000000         0.000             0.75
11504      0.000000         0.000             1.00
66         0.000000         0.375             0.00
16147      0.000000         0.250             0.00

---
----
----

### **2. Education Level:**

In [332]:
df["education_level"].value_counts()

education_level
Secondary       10099
Primary          3919
No education     3032
Higher           2950
Name: count, dtype: int64

The feature **Education Level**, an **ordinal categorical variable** strongly correlated with PPD risk.

**Membership Functions and Fuzzy Sets:**

We maintain the use of a **Discrete Membership Function (Lookup Table)** to map each crisp category to a degree of PPD risk.
 
We will define three fuzzy sets based on the degree of risk:

  * **Low Education Risk (High Vulnerability):** Corresponds to 'No education' and 'Primary'.
  
  * **Medium Education Risk (Moderate Vulnerability):** Corresponds to 'Secondary' (the largest group).
  
  * **High Education Risk (Low Vulnerability/Reference):** Corresponds to 'Higher' education.

**Fuzzy Sets and Discrete Mapping:**

Since **Secondary** is the largest group, we must ensure the **Medium Risk** set is strongly associated with it. We also adjust the overlap to reflect that the jump from **Secondary** to **Higher** is a major reduction in PPD risk.

| Crisp Input Category (x) | PPD Risk Rationale | $\mu_{\text{Low\_Edu\_Risk}}$ | $\mu_{\text{Medium\_Edu\_Risk}}$ | $\mu_{\text{High\_Edu\_Risk}}$ |
| :--- | :--- | :--- | :--- | :--- |
| **No education** | Highest risk/vulnerability. | **1.0** | 0.0 | 0.0 |
| **Primary** | High risk, transitioning towards medium. | **0.7** | **0.3** | 0.0 |
| **Secondary** | Largest cohort, moderate risk/transition point. | **0.2** | **0.8** | 0.0 |
| **Higher** | Lowest risk (Reference Group). | 0.0 | **0.1** | **0.9** |

  * **Rationale for Overlap:**
      * **Primary (0.7/0.3):** The primary group is primarily low-education risk (0.7) but partially resembles the moderate (secondary) risk group (0.3).
      
      * **Secondary (0.2/0.8):** The majority of membership is in the Medium Risk set (0.8), acknowledging its position as the largest, modal group in your data. It retains slight membership in the low-risk set (0.2) to capture the boundary ambiguity.
      
      * **Higher (0.1/0.9):** This group is dominantly high-education risk (0.9), but we retain a minor link to the medium-risk group (0.1) as not all higher education is equal.

**Fuzzy Set Definition:**

A. Fuzzy Set: **Low Education Risk** ($\mu_{\text{Low\_Edu\_Risk}}$)

  * **Description:** Represents high vulnerability due to minimal or no formal schooling.
  
  * **Membership Function (Lookup):**
    > $$\mu_{\text{Low\_Edu\_Risk}}(x) = \begin{cases} 1.0 & \text{if } x = \text{'No education'} \\ 0.7 & \text{if } x = \text{'Primary'} \\ 0.2 & \text{if } x = \text{'Secondary'} \\ 0.0 & \text{if } x = \text{'Higher'} \end{cases}$$
  
  * **Shape:** Descending step function across the ordinal education scale.

B. Fuzzy Set: **Medium Education Risk** ($\mu_{\text{Medium\_Edu\_Risk}}$)

  * **Description:** Represents moderate vulnerability, concentrated on the Secondary level, which is the most common education status in the dataset.
  
  * **Membership Function (Lookup):**
    > $$\mu_{\text{Medium\_Edu\_Risk}}(x) = \begin{cases} 0.0 & \text{if } x = \text{'No education'} \\ 0.3 & \text{if } x = \text{'Primary'} \\ 0.8 & \text{if } x = \text{'Secondary'} \\ 0.1 & \text{if } x = \text{'Higher'} \end{cases}$$
  
  * **Shape:** Peak function centered at 'Secondary'.

C. Fuzzy Set: **High Education Risk** ($\mu_{\text{High\_Edu\_Risk}}$)

  * **Description:** Represents the lowest vulnerability group with the highest PPD protective factor.
  
  * **Membership Function (Lookup):**
    > $$\mu_{\text{High\_Edu\_Risk}}(x) = \begin{cases} 0.0 & \text{if } x = \text{'No education'} \\ 0.0 & \text{if } x = \text{'Primary'} \\ 0.0 & \text{if } x = \text{'Secondary'} \\ 0.9 & \text{if } x = \text{'Higher'} \end{cases}$$
  
  * **Shape:** Ascending step function concentrated at the 'Higher' level.

In [333]:
import numpy as np
import pandas as pd

# Define the Discrete Fuzzification Map:

fuzzy_map_edu = {
    'No education':       {'mu_edu_low_risk': 1.0, 'mu_edu_medium_risk': 0.0, 'mu_edu_high_risk': 0.0},
    'Primary':            {'mu_edu_low_risk': 0.7, 'mu_edu_medium_risk': 0.3, 'mu_edu_high_risk': 0.0},
    'Secondary':          {'mu_edu_low_risk': 0.2, 'mu_edu_medium_risk': 0.8, 'mu_edu_high_risk': 0.0},
    'Higher':             {'mu_edu_low_risk': 0.0, 'mu_edu_medium_risk': 0.1, 'mu_edu_high_risk': 0.9},
}

# Fuzzification Function

def fuzzify_categorical_level(df: pd.DataFrame, input_column: str, mapping: dict, prefix: str) -> pd.DataFrame:
    """
    Applies the discrete fuzzy mapping to a categorical column.
    
    Args:
        prefix: Used to name the new fuzzy columns (e.g., 'mu_edu_').
    """
    
    # Extract the fuzzy set names from the first category's mapping keys
    fuzzy_set_names = list(list(mapping.values())[0].keys())
    
    fuzzy_features = {}
    
    for name in fuzzy_set_names:
        # Map the column using a lambda to look up the correct value for each row
        fuzzy_features[name] = df[input_column].map(lambda x: mapping[x][name])

    return pd.DataFrame(fuzzy_features)

# Execute Fuzzification and Merge:

fuzzy_df_edu = fuzzify_categorical_level(df, 'education_level', fuzzy_map_edu, 'mu_edu_')

In [334]:
fuzzy_df_edu

       mu_edu_low_risk  mu_edu_medium_risk  mu_edu_high_risk
0                  0.2                 0.8               0.0
1                  0.7                 0.3               0.0
2                  0.2                 0.8               0.0
3                  0.2                 0.8               0.0
4                  0.7                 0.3               0.0
...                ...                 ...               ...
19995              0.2                 0.8               0.0
19996              0.7                 0.3               0.0
19997              0.7                 0.3               0.0
19998              0.2                 0.8               0.0
19999              1.0                 0.0               0.0

[20000 rows x 3 columns]

In [335]:
# Concatenate the new fuzzy features back to the fuzzy_df:
fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_edu], axis=1)

In [336]:
fuzzy_df.head(4)

,mu_age_young,mu_age_prime,mu_age_advanced,mu_edu_low_risk,mu_edu_medium_risk,mu_edu_high_risk
0,1.0,0.0,0.0,0.2,0.8,0.0
1,0.0,0.0,0.5,0.7,0.3,0.0
2,0.0,0.0,0.5,0.2,0.8,0.0
3,0.0,0.0,1.0,0.2,0.8,0.0

In [337]:
fuzzy_df.shape

(20000, 6)

In [ ]:
# Concatenate the new fuzzy features back to the original DataFrame
#df = pd.concat([df, fuzzy_df_edu], axis=1)

In [338]:
fuzzy_df.shape

(20000, 6)

----------
--------------
----------------

### **3. wealth_index:**

In [339]:
df["wealth_index"].value_counts()

wealth_index
Poorest    4506
Middle     4339
Poorer     3898
Richer     3893
Richest    3364
Name: count, dtype: int64

The **Wealth Index** is a crucial ordinal categorical variable, and its categories are the standard five quintiles used in Demographic and Health Surveys (DHS). We will define the fuzzy sets based on the established principle that PPD risk is highest in the lower wealth quintiles.


We will use a **Discrete Membership Function (Lookup Table)** to map each of the five wealth quintiles to a fixed degree of membership ($\mu$) in the three fuzzy risk sets defined below.

  * **High Poverty Risk (High Vulnerability):** Corresponds to the **Poorest** and **Poorer** quintiles.

  * **Medium Wealth Risk (Moderate Vulnerability):** Corresponds to the **Middle** quintile, representing the large transition group.
  
  * **Low Poverty Risk (Low Vulnerability/Reference):** Corresponds to the **Richer** and **Richest** quintiles.

**2\. Fuzzy Sets and Discrete Mapping:**

The mapping ensures a smooth, continuous transition of PPD risk across the discrete categories through controlled overlap.

| Crisp Input Category (x) | PPD Risk Rationale | $\mu_{\text{High\_Poverty}}$ | $\mu_{\text{Medium\_Wealth}}$ | $\mu_{\text{Low\_Poverty}}$ |
| :--- | :--- | :--- | :--- | :--- |
| **Poorest** | Highest risk/vulnerability. | **1.0** | 0.0 | 0.0 |
| **Poorer** | High risk, transitioning towards medium. | **0.7** | **0.3** | 0.0 |
| **Middle** | The central transition group. | **0.3** | **0.7** | 0.0 |
| **Richer** | Low risk, transitioning from medium. | 0.0 | **0.3** | **0.7** |
| **Richest** | Lowest risk (Reference Group). | 0.0 | 0.0 | **1.0** |

**3\. Detailed Fuzzy Set Definition:**

A. Fuzzy Set: **High Poverty Risk** ($\mu_{\text{High\_Poverty}}$)

  * **Description:** Captures mothers in the most vulnerable economic position. Full membership is assigned to **Poorest** and gradually decreases.
  
  * **Membership Function (Lookup):**
    > $$\mu_{\text{High\_Poverty}}(x) = \begin{cases} 1.0 & \text{if } x = \text{'Poorest'} \\ 0.7 & \text{if } x = \text{'Poorer'} \\ 0.3 & \text{if } x = \text{'Middle'} \\ 0.0 & \text{if } x \in \{\text{'Richer'}, \text{'Richest'}\} \end{cases}$$

B. Fuzzy Set: **Medium Wealth Risk** ($\mu_{\text{Medium\_Wealth}}$)

  * **Description:** Represents the moderate risk group, encompassing those who are marginally wealthy or marginally poor. This set peaks at **Middle** (0.7).
  
  * **Membership Function (Lookup):**
    > $$\mu_{\text{Medium\_Wealth}}(x) = \begin{cases} 0.0 & \text{if } x = \text{'Poorest'} \\ 0.3 & \text{if } x = \text{'Poorer'} \\ 0.7 & \text{if } x = \text{'Middle'} \\ 0.3 & \text{if } x = \text{'Richer'} \\ 0.0 & \text{if } x = \text{'Richest'} \end{cases}$$

C. Fuzzy Set: **Low Poverty Risk** ($\mu_{\text{Low\_Poverty}}$)

  * **Description:** Represents mothers with significant economic stability, acting as the protective/reference group. Full membership is assigned to **Richest**.
  
  * **Membership Function (Lookup):**
    > $$\mu_{\text{Low\_Poverty}}(x) = \begin{cases} 0.0 & \text{if } x \in \{\text{'Poorest'}, \text{'Poorer'}, \text{'Middle'}\} \\ 0.7 & \text{if } x = \text{'Richer'} \\ 1.0 & \text{if } x = \text{'Richest'} \end{cases}$$

In [340]:
import numpy as np
import pandas as pd

# Define the Discrete Fuzzification Map

fuzzy_map_wealth = {
    'Poorest':  {'mu_wealth_high_poverty': 1.0, 'mu_wealth_medium_wealth': 0.0, 'mu_wealth_low_poverty': 0.0},
    'Poorer':   {'mu_wealth_high_poverty': 0.7, 'mu_wealth_medium_wealth': 0.3, 'mu_wealth_low_poverty': 0.0},
    'Middle':   {'mu_wealth_high_poverty': 0.3, 'mu_wealth_medium_wealth': 0.7, 'mu_wealth_low_poverty': 0.0},
    'Richer':   {'mu_wealth_high_poverty': 0.0, 'mu_wealth_medium_wealth': 0.3, 'mu_wealth_low_poverty': 0.7},
    'Richest':  {'mu_wealth_high_poverty': 0.0, 'mu_wealth_medium_wealth': 0.0, 'mu_wealth_low_poverty': 1.0},
}

# Fuzzification Function

def fuzzify_categorical_level(df: pd.DataFrame, input_column: str, mapping: dict) -> pd.DataFrame:
    """
    Applies the discrete fuzzy mapping to a categorical column.
    """
    
    # Extract the fuzzy set names from the first category's mapping keys
    first_key = list(mapping.keys())[0]
    fuzzy_set_names = list(mapping[first_key].keys())
    
    fuzzy_features = {}
    
    for name in fuzzy_set_names:
        # Map the column using a lambda to look up the correct value for each row
        fuzzy_features[name] = df[input_column].map(lambda x: mapping[x][name])

    return pd.DataFrame(fuzzy_features)

# Execute Fuzzification and Merge

fuzzy_df_wealth = fuzzify_categorical_level(df, 'wealth_index', fuzzy_map_wealth)

In [341]:
fuzzy_df_wealth.head(2)

   mu_wealth_high_poverty  mu_wealth_medium_wealth  mu_wealth_low_poverty
0                     0.0                      0.3                    0.7
1                     0.0                      0.3                    0.7

In [342]:
fuzzy_df_wealth.shape

(20000, 3)

In [343]:
fuzzy_df.shape

(20000, 6)

In [344]:
# Concatenate the new fuzzy features back to the fuzzy_df
fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_wealth], axis=1)

In [345]:
fuzzy_df.head(2).shape

(2, 9)

In [ ]:
# Concatenate the new fuzzy features back to the original DataFrame
# df = pd.concat([df, fuzzy_df_wealth], axis=1)

-------------
------------
------------

### **4. monthly_household_income:**

In [346]:
df["monthly_household_income"].describe()

count     20000.000000
mean      45830.999300
std       39026.142782
min        8000.000000
25%       18000.000000
50%       31644.500000
75%       59835.250000
max      180000.000000
Name: monthly_household_income, dtype: float64

The official data sources (NDHS 2022, Nepal Census 2021, WHO Reports) guide the definition of **poverty lines** or **vulnerability thresholds** in the Nepali context. Using these established thresholds makes the fuzzy sets *meaningful* for health practitioners.

We will define the **Low Income** set based on a threshold for severe financial vulnerability (e.g., minimum wage or extreme poverty line), and the **High Income** set based on an income level that confers significant *protective* health effects.

| Fuzzy Set | Contextual Rationale | Revised Boundary Reference |
| :--- | :--- | :--- |
| **Low Income** | **Acute Poverty/Risk:** Income insufficient for basic necessities and routine medical care. Membership = 1 should cover the minimum income up to a critical poverty threshold. | Max $\mu=1$ up to **NPR 20,000**. Support ends at **NPR 45,000** (close to the overall mean). |
| **Moderate Income** | **Working Poor/Middle Class:** Able to afford necessities but vulnerable to health shocks. Peaks at **NPR 50,000** (a round figure slightly above the mean/median). | Peak at **NPR 50,000**. Support ranges from **NPR 30,000** to **NPR 100,000**. |
| **High Income** | **Protective/Low Risk:** Disposable income ensures access to private/quality care, reducing financial stress. | Max $\mu=1$ from **NPR 120,000**. Support starts at **NPR 80,000**. |

**Fuzzy Sets and Membership Functions:**

The minimum income remains $8,000$ and the maximum remains $180,000$.

A. Fuzzy Set: **Low Income** ($\mu_{\text{Low\_Inc}}$)

  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters (NPR):**
      * $a = 8,000$ (Min Income)
      * $b = 20,000$ (Start of Core/Clinical Threshold)
      * $c = 20,000$ (End of Core)
      * $d = 45,000$ (Support End/Overlap with Moderate)
  
  * **Mathematical Formula (Support Slope):**
    > $$\mu_{\text{Low\_Inc}}(x) = \frac{45000-x}{45000-20000} \quad \text{for } 20000 < x < 45000$$

B. Fuzzy Set: **Moderate Income** ($\mu_{\text{Mod\_Inc}}$)

  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  
  * **Parameters (NPR):**
      * $a = 30,000$ (Support Start/Overlap with Low)
      * $b = 50,000$ (Peak/Contextual Center)
      * $c = 100,000$ (Support End/Overlap with High)
  
  * **Mathematical Formula (Right Slope):**
    > $$\mu_{\text{Mod\_Inc}}(x) = \frac{100000-x}{100000-50000} \quad \text{for } 50000 < x < 100000$$

C. Fuzzy Set: **High Income** ($\mu_{\text{High\_Inc}}$)

  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters (NPR):**
      * $a = 80,000$ (Support Start/Overlap with Moderate)
      * $b = 120,000$ (Start of Core/Protective Threshold)
      * $c = 180,000$ (Max Income)
      * $d = 180,000$ (Max Income)
  
  * **Mathematical Formula (Ascent Slope):**
    > $$\mu_{\text{High\_Inc}}(x) = \frac{x-80000}{120000-80000} \quad \text{for } 80000 < x < 120000$$

In [347]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe and CONTEXTUAL PARAMETERS ---

# Contextually Relevant Parameters (based on clinical/economic relevance, not just sample quartiles)
MIN_INCOME = 8000.0
MAX_INCOME = 180000.0

# 1. Low Income (Trap): Full membership up to 20k, 0 at 45k
low_inc_params = [MIN_INCOME, 20000, 20000, 45000] 

# 2. Moderate Income (Tri): Starts 30k, Peaks 50k, Ends 100k
mod_inc_params = [30000, 50000, 100000]

# 3. High Income (Trap): 0 at 80k, Full membership from 120k
high_inc_params = [80000, 120000, MAX_INCOME, MAX_INCOME]

# Define the universe of discourse
income_universe = np.arange(MIN_INCOME, MAX_INCOME + 1, 100) 

# Compute the membership functions (MFs) across the defined universe
low_inc_mf = fuzz.trapmf(income_universe, low_inc_params)
mod_inc_mf = fuzz.trimf(income_universe, mod_inc_params)
high_inc_mf = fuzz.trapmf(income_universe, high_inc_params)

In [348]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_income_contextual(df: pd.DataFrame, income_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire income column using contextual MFs."""
    
    # Apply interpolation to the entire income column
    mu_low = [
        fuzz.interp_membership(income_universe, low_inc_mf, x)
        for x in df['monthly_household_income']
    ]
    
    mu_mod = [
        fuzz.interp_membership(income_universe, mod_inc_mf, x)
        for x in df['monthly_household_income']
    ]
    
    mu_high = [
        fuzz.interp_membership(income_universe, high_inc_mf, x)
        for x in df['monthly_household_income']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_inc_low': mu_low,
        'mu_inc_mod': mu_mod,
        'mu_inc_high': mu_high
    })

In [349]:
# Execute Fuzzification:
fuzzy_df_inc = fuzzify_income_contextual(df, income_universe)
fuzzy_df_inc

       mu_inc_low  mu_inc_mod  mu_inc_high
0         0.00000     0.97912          0.0
1         0.20932     0.48835          0.0
2         0.00000     0.75000          0.0
3         0.81400     0.00000          0.0
4         0.00000     0.76206          0.0
...           ...         ...          ...
19995     0.85528     0.00000          0.0
19996     0.90732     0.00000          0.0
19997     0.82875     0.00000          0.0
19998     0.51736     0.10330          0.0
19999     0.00000     0.58818          0.0

[20000 rows x 3 columns]

In [350]:
fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_inc], axis=1)
fuzzy_df.shape

(20000, 12)

In [ ]:
#df = pd.concat([df, fuzzy_df_inc], axis=1)

-----------
-------------
-------------

### **5. food_security:**

In [351]:
df["food_security"].value_counts()

food_security
Secure                 8840
Mildly insecure        4605
Moderately insecure    3390
Severely insecure      3165
Name: count, dtype: int64

Higher food insecurity directly translates to higher chronic stress, poorer nutritional status, and therefore **higher PPD risk**.

We will define three fuzzy sets based on the degree of PPD risk, using a **Discrete Membership Function (Lookup Table)**.

**Membership Functions and Fuzzy Sets:**

**Input Feature:** `food_security` (Ordinal Categorical)
**Fuzzy Sets (Output Features):**

1.  **High Food Security Risk** ($\mu_{\text{fs\_high\_risk}}$): Associated with 'Severely insecure' and 'Moderately insecure'.

2.  **Moderate Food Security Risk** ($\mu_{\text{fs\_mod\_risk}}$): Associated with 'Mildly insecure', serving as the primary transition point.

3.  **Low Food Security Risk** ($\mu_{\text{fs\_low\_risk}}$): Associated with 'Secure', acting as the protective/reference group.

| Crisp Input Category (x) | PPD Risk Rationale (Nepal Context) | $\mu_{\text{fs\_high\_risk}}$ | $\mu_{\text{fs\_mod\_risk}}$ | $\mu_{\text{fs\_low\_risk}}$ |
| :--- | :--- | :--- | :--- | :--- |
| **Severely insecure** | Full Risk: Acute inability to meet food needs; major stressor. | **1.0** | 0.0 | 0.0 |
| **Moderately insecure** | Very High Risk: Significant reduction in quality/quantity; partial coping. | **0.8** | **0.2** | 0.0 |
| **Mildly insecure** | Moderate Risk: Daily worries/minor compromises on quality; high ambiguity. | **0.3** | **0.7** | 0.0 |
| **Secure** | Lowest Risk: Stable, protective socio-economic status. | 0.0 | 0.0 | **1.0** |

**Detailed Fuzzy Set Definition:**

The membership values are based on the assumption that the gradient of PPD risk closely follows the gradient of food insecurity severity.

A. Fuzzy Set: **High Food Security Risk** ($\mu_{\text{fs\_high\_risk}}$)

  * **Description:** Represents mothers whose food insecurity level poses the most serious, acute threat to their mental well-being (e.g., severe nutrient deficiency, constant worry).
  
  * **Membership Function (Lookup):**
    > $$\mu_{\text{fs\_high\_risk}}(x) = \begin{cases} 1.0 & \text{if } x = \text{'Severely insecure'} \\ 0.8 & \text{if } x = \text{'Moderately insecure'} \\ 0.3 & \text{if } x = \text{'Mildly insecure'} \\ 0.0 & \text{if } x = \text{'Secure'} \end{cases}$$
  
  * **Shape:** Steeply descending step function across the security scale.

B. Fuzzy Set: **Moderate Food Security Risk** ($\mu_{\text{fs\_mod\_risk}}$)

  * **Description:** Represents the transition group where mothers must actively manage or cope with financial stress related to food. Full membership is assigned to 'Mildly insecure' to reflect this category as the modal risk point.
  
  * **Membership Function (Lookup):**
    > $$\mu_{\text{fs\_mod\_risk}}(x) = \begin{cases} 0.0 & \text{if } x = \text{'Severely insecure'} \\ 0.2 & \text{if } x = \text{'Moderately insecure'} \\ 0.7 & \text{if } x = \text{'Mildly insecure'} \\ 0.0 & \text{if } x = \text{'Secure'} \end{cases}$$
  
  * **Shape:** Peak function centered at 'Mildly insecure'.

C. Fuzzy Set: **Low Food Security Risk** ($\mu_{\text{fs\_low\_risk}}$)

  * **Description:** Represents mothers with stable food access, serving as the strongest protective factor in the PPD model.
  
  * **Membership Function (Lookup):**
    > $$\mu_{\text{fs\_low\_risk}}(x) = \begin{cases} 0.0 & \text{if } x \in \{\text{'Severely insecure'}, \text{'Moderately insecure'}, \text{'Mildly insecure'}\} \\ 1.0 & \text{if } x = \text{'Secure'} \end{cases}$$
  
  * **Shape:** Step function concentrating membership at the highest security level.

In [352]:
import numpy as np
import pandas as pd

In [245]:
# Define the Discrete Fuzzification Map:

fuzzy_map_fs = {
    'Severely insecure':   {'mu_fs_high_risk': 1.0, 'mu_fs_mod_risk': 0.0, 'mu_fs_low_risk': 0.0},
    'Moderately insecure': {'mu_fs_high_risk': 0.8, 'mu_fs_mod_risk': 0.2, 'mu_fs_low_risk': 0.0},
    'Mildly insecure':     {'mu_fs_high_risk': 0.3, 'mu_fs_mod_risk': 0.7, 'mu_fs_low_risk': 0.0},
    'Secure':              {'mu_fs_high_risk': 0.0, 'mu_fs_mod_risk': 0.0, 'mu_fs_low_risk': 1.0},
}

In [353]:
# Fuzzification Function

def fuzzify_categorical_level(df: pd.DataFrame, input_column: str, mapping: dict) -> pd.DataFrame:
    """
    Applies the discrete fuzzy mapping to a categorical column.
    """
    
    # Extract the fuzzy set names from the first category's mapping keys
    first_key = list(mapping.keys())[0]
    fuzzy_set_names = list(mapping[first_key].keys())
    
    fuzzy_features = {}
    
    for name in fuzzy_set_names:
        # Use pandas map for efficiency
        fuzzy_features[name] = df[input_column].map(lambda x: mapping[x][name])

    return pd.DataFrame(fuzzy_features)

In [354]:
fuzzy_df.shape

(20000, 12)

In [355]:
# Execute Fuzzification and Merge

fuzzy_df_fs = fuzzify_categorical_level(df, 'food_security', fuzzy_map_fs)
fuzzy_df_fs

       mu_fs_high_risk  mu_fs_mod_risk  mu_fs_low_risk
0                  0.0             0.0             1.0
1                  0.8             0.2             0.0
2                  0.3             0.7             0.0
3                  0.3             0.7             0.0
4                  0.0             0.0             1.0
...                ...             ...             ...
19995              0.3             0.7             0.0
19996              0.8             0.2             0.0
19997              0.3             0.7             0.0
19998              0.3             0.7             0.0
19999              0.0             0.0             1.0

[20000 rows x 3 columns]

In [356]:
fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_fs], axis=1)

In [357]:
fuzzy_df.shape

(20000, 15)

In [358]:
fuzzy_df.head(3)

,mu_age_young,mu_age_prime,mu_age_advanced,mu_edu_low_risk,mu_edu_medium_risk,mu_edu_high_risk,mu_wealth_high_poverty,mu_wealth_medium_wealth,mu_wealth_low_poverty,mu_inc_low,mu_inc_mod,mu_inc_high,mu_fs_high_risk,mu_fs_mod_risk,mu_fs_low_risk
0,1.0,0.0,0.0,0.2,0.8,0.0,0.0,0.3,0.7,0.00000,0.97912,0.0,0.0,0.0,1.0
1,0.0,0.0,0.5,0.7,0.3,0.0,0.0,0.3,0.7,0.20932,0.48835,0.0,0.8,0.2,0.0
2,0.0,0.0,0.5,0.2,0.8,0.0,0.3,0.7,0.0,0.00000,0.75000,0.0,0.3,0.7,0.0

In [ ]:
# Concatenate the new fuzzy features back to the original DataFrame
#df = pd.concat([df, fuzzy_df_fs], axis=1)

-----------------
-----
------

### **6. housing_quality:**

In [359]:
df["housing_quality"].describe()

count    20000.000000
mean         5.582200
std          2.042878
min          1.000000
25%          4.000000
50%          6.000000
75%          7.000000
max         10.000000
Name: housing_quality, dtype: float64

The **Housing Quality** score is a **continuous numerical variable** (ranging from 1 to 10) that captures the living environment's potential as a stressor, which is highly relevant to PPD risk in the Nepali context. Poor housing quality (e.g., lack of sanitation, overcrowding, poor structural integrity) contributes significantly to maternal stress and disease exposure, increasing PPD risk.

We will fuzzify this score using **Trapezoidal** and **Triangular** membership functions, mapping the score to the degree of associated PPD risk.

The input is a continuous score from **1 (worst)** to **10 (best)**, with a median of **6**. We must define the fuzzy sets based on how housing quality contributes to **vulnerability** (risk) versus **protection** (low risk).

**We will define three fuzzy sets based on the degree of PPD risk:**

  * **Low Housing Quality (High Risk):** Scores indicating substandard living conditions.
  
  * **Moderate Housing Quality (Medium Risk):** Scores around the median, reflecting typical conditions with potential vulnerabilities.
  
  * **High Housing Quality (Low Risk/Reference):** Scores indicating excellent, protective living conditions.

In the Nepali context, particularly informed by NDHS and sanitation/housing reports, a score of 1-3 often indicates severe deprivation (high risk), while a score of 8-10 indicates a high-quality, protective environment (low risk).

| Fuzzy Set | Contextual Rationale | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Low Quality** | **Acute Risk:** Unsafe, unsanitary, or overcrowded housing conditions. | $\le 3$ | $[1, 6]$ |
| **Moderate Quality** | **Medium Risk:** Meets basic standards but lacks comfort/stability; highly common. | $\approx 6$ (Median) | $[4, 8]$ |
| **High Quality** | **Low Risk/Protective:** Provides safety, sanitation, space, and comfort; protective factor. | $\ge 9$ | $[7, 10]$ |


A. Fuzzy Set: **Low Housing Quality** ($\mu_{\text{Low\_HQ}}$)

  * **Description:** Represents high PPD risk due to environmental stress. Full membership is assigned to the lowest scores.
  
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters:** $a=1, b=3, c=3, d=6$.
    > $$\mu_{\text{Low\_HQ}}(x) = \begin{cases} 1 & \text{if } x \le 3 \\ \frac{6-x}{6-3} & \text{if } 3 < x < 6 \\ 0 & \text{if } x \ge 6 \end{cases}$$

B. Fuzzy Set: **Moderate Housing Quality** ($\mu_{\text{Mod\_HQ}}$)

  * **Description:** Represents moderate PPD risk; the largest transition group centered near the median score of 6.
  
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  
  * **Parameters:** $a=4, b=6, c=8$.
    > $$\mu_{\text{Mod\_HQ}}(x) = \text{trimf}(x; 4, 6, 8)$$

C. Fuzzy Set: **High Housing Quality** ($\mu_{\text{High\_HQ}}$)

  * **Description:** Represents low PPD risk; protective environmental factor. Full membership is assigned to the highest scores.
  
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters:** $a=7, b=9, c=10, d=10$.
    > $$\mu_{\text{High\_HQ}}(x) = \begin{cases} 0 & \text{if } x \le 7 \\ \frac{x-7}{9-7} & \text{if } 7 < x < 9 \\ 1 & \text{if } x \ge 9 \end{cases}$$

In [360]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# We need to define the universe of discourse (1 to 10) for skfuzzy.
MIN_SCORE = 1.0
MAX_SCORE = 10.0
# Using steps of 0.1 for smooth interpolation
quality_universe = np.arange(MIN_SCORE, MAX_SCORE + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets: 

# A. Low Quality (Trap): Full membership up to 3, 0 at 6
low_hq_params = [1.0, 3.0, 3.0, 6.0] 

# B. Moderate Quality (Tri): Starts 4, Peaks 6 (Median), Ends 8
mod_hq_params = [4.0, 6.0, 8.0]

# C. High Quality (Trap): 0 at 7, Full membership from 9
high_hq_params = [7.0, 9.0, 10.0, 10.0]

# Pre-compute the membership functions (MFs): 
low_hq_mf = fuzz.trapmf(quality_universe, low_hq_params)
mod_hq_mf = fuzz.trimf(quality_universe, mod_hq_params)
high_hq_mf = fuzz.trapmf(quality_universe, high_hq_params)

In [361]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_housing_quality(df: pd.DataFrame, quality_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire housing_quality column."""
    
    # Apply interpolation to the entire column
    # Use global MFs computed in step 2
    mu_low = [
        fuzz.interp_membership(quality_universe, low_hq_mf, x)
        for x in df['housing_quality']
    ]
    
    mu_mod = [
        fuzz.interp_membership(quality_universe, mod_hq_mf, x)
        for x in df['housing_quality']
    ]
    
    mu_high = [
        fuzz.interp_membership(quality_universe, high_hq_mf, x)
        for x in df['housing_quality']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_hq_low': mu_low,
        'mu_hq_mod': mu_mod,
        'mu_hq_high': mu_high
    })

In [362]:
# Execute Fuzzification and Merge

fuzzy_df_hq = fuzzify_housing_quality(df, quality_universe)

fuzzy_df_hq.shape

(20000, 3)

In [363]:
fuzzy_df_hq.head(3)

   mu_hq_low     mu_hq_mod  mu_hq_high
0   0.000000  0.000000e+00         1.0
1   0.000000  3.552714e-15         0.5
2   0.333333  5.000000e-01         0.0

In [364]:
fuzzy_df.shape

(20000, 15)

In [365]:
fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_hq], axis=1)
display(fuzzy_df.shape)

(20000, 18)

In [ ]:
#df = pd.concat([df, fuzzy_df_hq], axis=1)
#display(df.shape)

(20000, 35)

In [366]:
display(fuzzy_df.head())

,mu_age_young,mu_age_prime,mu_age_advanced,mu_edu_low_risk,mu_edu_medium_risk,mu_edu_high_risk,mu_wealth_high_poverty,mu_wealth_medium_wealth,mu_wealth_low_poverty,mu_inc_low,mu_inc_mod,mu_inc_high,mu_fs_high_risk,mu_fs_mod_risk,mu_fs_low_risk,mu_hq_low,mu_hq_mod,mu_hq_high
0,1.0,0.0,0.0,0.2,0.8,0.0,0.0,0.3,0.7,0.00000,0.97912,0.0,0.0,0.0,1.0,0.000000,0.000000e+00,1.0
1,0.0,0.0,0.5,0.7,0.3,0.0,0.0,0.3,0.7,0.20932,0.48835,0.0,0.8,0.2,0.0,0.000000,3.552714e-15,0.5
2,0.0,0.0,0.5,0.2,0.8,0.0,0.3,0.7,0.0,0.00000,0.75000,0.0,0.3,0.7,0.0,0.333333,5.000000e-01,0.0
3,0.0,0.0,1.0,0.2,0.8,0.0,0.7,0.3,0.0,0.81400,0.00000,0.0,0.3,0.7,0.0,0.666667,1.332268e-15,0.0
4,0.0,0.0,1.0,0.7,0.3,0.0,0.0,0.3,0.7,0.00000,0.76206,0.0,0.0,0.0,1.0,0.000000,3.552714e-15,0.5

-------------
-----------
---------------

### **7. financial_stress_level:**

In [367]:
df["financial_stress_level"].describe()

count    20000.00000
mean         5.01695
std          2.95508
min          0.00000
25%          3.00000
50%          5.00000
75%          7.00000
max         10.00000
Name: financial_stress_level, dtype: float64

We will fuzzify this score using **Trapezoidal** and **Triangular** membership functions, mapping the score directly to the associated PPD risk.

The input is a continuous score from **0 (lowest stress)** to **10 (highest stress)**, with a median of **5**. Since PPD risk increases with stress, the fuzzification sets will be structured such that the high-score end corresponds to the high-risk fuzzy set.

We will define three fuzzy sets based on the degree of PPD risk:

  * **Low Stress Level (Low Risk/Reference):** Scores indicating minimal financial worry.
  * **Moderate Stress Level (Medium Risk):** Scores around the median, reflecting the most common level of financial pressure.
  * **High Stress Level (High Risk):** Scores indicating severe, debilitating financial worry.

Given that this is a stress score, the quartiles from your data (Q1=3, Median=5, Q3=7) are highly informative and contextually relevant for setting the boundaries of low, moderate, and high stress experienced by the population.

| Fuzzy Set (Stress Score) | Contextual Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Low Stress** | **Low Risk/Protective:** Minimal financial concern. | $\le 2$ | $[0, 4]$ |
| **Moderate Stress** | **Medium Risk:** Common financial worries, manageable. | $\approx 5$ (Median) | $[3, 7]$ |
| **High Stress** | **High Risk:** Severe, persistent financial strain, a major PPD predictor. | $\ge 8$ | $[6, 10]$ |

A. Fuzzy Set: **Low Stress Level** ($\mu_{\text{Low\_Stress}}$)

  * **Description:** Represents low PPD risk due to minimal financial strain.
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=0, b=2, c=2, d=4$.
    > $$\mu_{\text{Low\_Stress}}(x) = \begin{cases} 1 & \text{if } x \le 2 \\ \frac{4-x}{4-2} & \text{if } 2 < x < 4 \\ 0 & \text{if } x \ge 4 \end{cases}$$

B. Fuzzy Set: **Moderate Stress Level** ($\mu_{\text{Mod\_Stress}}$)

  * **Description:** Represents moderate PPD risk; the central, highly ambiguous group.
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  * **Parameters:** $a=3, b=5, c=7$.
    > $$\mu_{\text{Mod\_Stress}}(x) = \text{trimf}(x; 3, 5, 7)$$

C. Fuzzy Set: **High Stress Level** ($\mu_{\text{High\_Stress}}$)

  * **Description:** Represents high PPD risk; severe, chronic financial stress.
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=6, b=8, c=10, d=10$.
    > $$\mu_{\text{High\_Stress}}(x) = \begin{cases} 0 & \text{if } x \le 6 \\ \frac{x-6}{8-6} & \text{if } 6 < x < 8 \\ 1 & \text{if } x \ge 8 \end{cases}$$

In [370]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (0 to 10)
MIN_SCORE = 0.0
MAX_SCORE = 10.0
# Using steps of 0.1 for smooth interpolation
stress_universe = np.arange(MIN_SCORE, MAX_SCORE + 0.1, 0.1) 

# Define the Parameters for Fuzzy Sets (based on Q1=3, Median=5, Q3=7)

# A. Low Stress (Trap): Full membership up to 2, 0 at 4
low_stress_params = [0.0, 2.0, 2.0, 4.0] 

# B. Moderate Stress (Tri): Starts 3 (Q1), Peaks 5 (Median), Ends 7 (Q3)
mod_stress_params = [3.0, 5.0, 7.0]

# C. High Stress (Trap): 0 at 6, Full membership from 8
high_stress_params = [6.0, 8.0, 10.0, 10.0]

# Pre-compute the membership functions (MFs)
low_stress_mf = fuzz.trapmf(stress_universe, low_stress_params)
mod_stress_mf = fuzz.trimf(stress_universe, mod_stress_params)
high_stress_mf = fuzz.trapmf(stress_universe, high_stress_params)

In [371]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_financial_stress(df: pd.DataFrame, stress_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire financial_stress_level column."""
    
    # Apply interpolation to the entire column
    mu_low = [
        fuzz.interp_membership(stress_universe, low_stress_mf, x)
        for x in df['financial_stress_level']
    ]
    
    mu_mod = [
        fuzz.interp_membership(stress_universe, mod_stress_mf, x)
        for x in df['financial_stress_level']
    ]
    
    mu_high = [
        fuzz.interp_membership(stress_universe, high_stress_mf, x)
        for x in df['financial_stress_level']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_stress_low': mu_low,
        'mu_stress_mod': mu_mod,
        'mu_stress_high': mu_high
    })

In [372]:
fuzzy_df.shape

(20000, 18)

In [373]:
# Execute Fuzzification and Merge

fuzzy_df_stress = fuzzify_financial_stress(df, stress_universe)
print(fuzzy_df_stress.shape)

(20000, 3)

In [374]:
fuzzy_df= pd.concat([fuzzy_df, fuzzy_df_stress], axis=1)
print(fuzzy_df.shape)

(20000, 21)

In [ ]:
#df = pd.concat([df, fuzzy_df_stress], axis=1)
#print(df.shape)

(20000, 38)

--------
------
-----

### **8. parity:**

In [375]:
df["parity"].describe()

count    20000.000000
mean         1.630050
std          1.461093
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          8.000000
Name: parity, dtype: float64

**Parity**, which is the number of children a woman has given birth to, is a significant obstetric factor. In the context of maternal mental health, particularly in Nepal (as noted in NDHS reports):

  * **Zero Parity (Nulliparous):** Often associated with **higher anxiety** related to the first-time motherhood experience.
  
  * **High Parity:** Associated with **higher risk** due to physical strain, increased family workload, financial burden, and limited resources per child.

The data is **continuous/discrete numerical** (0 to 8, typically integer), with a median of **1**.

We will define three fuzzy sets based on the degree of PPD risk, prioritizing contextual and clinical findings over strictly statistical quartiles.

We will use Trapezoidal and Triangular membership functions across the parity range of 0 to 8.

  * **Low Parity (Risk/Transition):** Includes mothers with zero or one child (primiparous), covering the anxiety risk factor.
  * **Optimal Parity (Low Risk/Reference):** Typically considered 2-3 children, aligning with national fertility goals and the best balance of resources.
  * **High Parity (High Risk):** Mothers with 4 or more children, aligning with higher workload and financial/physical strain.


We set the boundaries based on common clinical and demographic classifications of parity:

| Fuzzy Set (Parity) | Contextual Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Low Parity** | **Initial Risk/Anxiety:** Risk associated with first-time mothers (0-1). | $\le 1$ | $[0, 3]$ |
| **Optimal Parity** | **Reference/Low Risk:** The preferred family size with established support (2-3). | $2$ | $[1, 4]$ |
| **High Parity** | **High Risk/Strain:** Associated with exhaustion, financial strain, and reduced resources (4+). | $\ge 5$ | $[3, 8]$ |

A. Fuzzy Set: **Low Parity** ($\mu_{\text{Low\_P}}$)

  * **Description:** Covers the unique stress of first-time motherhood and low family size.
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=0, b=1, c=1, d=3$.
    > $$\mu_{\text{Low\_P}}(x) = \begin{cases} 1 & \text{if } x \le 1 \\ \frac{3-x}{3-1} & \text{if } 1 < x < 3 \\ 0 & \text{if } x \ge 3 \end{cases}$$

B. Fuzzy Set: **Optimal Parity** ($\mu_{\text{Opt\_P}}$)

  * **Description:** The low-risk reference group, peaking at the common ideal family size.
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  * **Parameters:** $a=1, b=2, c=4$.
    > $$\mu_{\text{Opt\_P}}(x) = \text{trimf}(x; 1, 2, 4)$$

C. Fuzzy Set: **High Parity** ($\mu_{\text{High\_P}}$)

  * **Description:** Represents high PPD risk due to the cumulative physical and psychological burden of multiple births.
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=3, b=5, c=8, d=8$.
    > $$\mu_{\text{High\_P}}(x) = \begin{cases} 0 & \text{if } x \le 3 \\ \frac{x-3}{5-3} & \text{if } 3 < x < 5 \\ 1 & \text{if } x \ge 5 \end{cases}$$

In [376]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (0 to 8): 
MIN_PARITY = 0.0
MAX_PARITY = 8.0
# Using steps of 0.1 for smooth interpolation
parity_universe = np.arange(MIN_PARITY, MAX_PARITY + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets

# A. Low Parity (Trap): Full membership up to 1, 0 at 3
low_p_params = [0.0, 1.0, 1.0, 3.0] 

# B. Optimal Parity (Tri): Starts 1, Peaks 2, Ends 4
opt_p_params = [1.0, 2.0, 4.0]

# C. High Parity (Trap): 0 at 3, Full membership from 5
high_p_params = [3.0, 5.0, 8.0, 8.0]

# Pre-compute the membership functions (MFs)
low_p_mf = fuzz.trapmf(parity_universe, low_p_params)
opt_p_mf = fuzz.trimf(parity_universe, opt_p_params)
high_p_mf = fuzz.trapmf(parity_universe, high_p_params)

In [377]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_parity(df: pd.DataFrame, parity_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire parity column."""
    
    # Apply interpolation to the entire column
    mu_low = [
        fuzz.interp_membership(parity_universe, low_p_mf, x)
        for x in df['parity']
    ]
    
    mu_opt = [
        fuzz.interp_membership(parity_universe, opt_p_mf, x)
        for x in df['parity']
    ]
    
    mu_high = [
        fuzz.interp_membership(parity_universe, high_p_mf, x)
        for x in df['parity']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_parity_low': mu_low,
        'mu_parity_opt': mu_opt,
        'mu_parity_high': mu_high
    })

In [378]:
# Execute Fuzzification and Merge: 

fuzzy_df_parity = fuzzify_parity(df, parity_universe)
print(fuzzy_df_parity.shape)

#df = pd.concat([df, fuzzy_df_parity], axis=1)
#print(df.shape)

(20000, 3)

In [379]:
fuzzy_df= pd.concat([fuzzy_df, fuzzy_df_parity], axis=1)
print(fuzzy_df.shape)

(20000, 24)

--------------
--------------------
---------------

### **9. anc_visits:**

In [380]:
df["anc_visits"].describe()

count    20000.000000
mean         5.497250
std          2.422042
min          0.000000
25%          4.000000
50%          6.000000
75%          7.000000
max         12.000000
Name: anc_visits, dtype: float64

This is a critical feature, as **Antenatal Care (ANC) Visits** is a standard health service utilization metric and a major protective factor against adverse maternal outcomes, including Postpartum Depression (PPD).

The variable `anc_visits` is a **continuous/discrete numerical variable** ranging from 0 to 12. In the context of PPD, the risk is **inversely proportional** to the number of adequate ANC visits.

We must base the fuzzification on **World Health Organization (WHO) and Ministry of Health (MoH) standards** which are directly referenced in Nepali health policy (like the NDHS).

The WHO guideline (adopted by Nepal) recommends a minimum of **8 ANC contacts** for positive pregnancy experience and optimal outcomes. This standard provides the primary contextual anchor for our fuzzy sets.

We will define three fuzzy sets based on the degree of compliance with clinical guidelines, which reflects the PPD risk:

  * **Inadequate ANC (High Risk):** Visits below the minimum standard.
  
  * **Sufficient ANC (Medium Risk/Transition):** Visits meeting the previous 4-visit standard, but below the current optimal 8-visit standard.
  
  * **Optimal ANC (Low Risk/Reference):** Visits meeting or exceeding the current international/national standard of 8 contacts.

**Contextual Parameter Setting:**

The fuzzy set boundaries are defined by the clinical standards:

| Fuzzy Set (Visits) | Clinical Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Inadequate ANC** | **High Risk:** Below the 4-visit standard (previously considered standard). Represents neglect/poor access. | $\le 3$ | $[0, 5]$ |
| **Sufficient ANC** | **Medium Risk:** Meets the traditional 4-visit standard but falls short of the optimal 8-visit standard. | $5$ | $[3, 8]$ |
| **Optimal ANC** | **Low Risk/Protective:** Meets or exceeds the WHO-recommended 8-contact standard. | $\ge 9$ | $[7, 12]$ |

**Detailed Fuzzy Set Definition:**

We use Trapezoidal and Triangular membership functions across the range of 0 to 12.

A. Fuzzy Set: **Inadequate ANC** ($\mu_{\text{Inad\_ANC}}$)

  * **Description:** Represents high PPD risk due to missed opportunities for screening, counseling, and nutritional support.
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=0, b=3, c=3, d=5$.
    > $$\mu_{\text{Inad\_ANC}}(x) = \begin{cases} 1 & \text{if } x \le 3 \\ \frac{5-x}{5-3} & \text{if } 3 < x < 5 \\ 0 & \text{if } x \ge 5 \end{cases}$$

B. Fuzzy Set: **Sufficient ANC** ($\mu_{\text{Suff\_ANC}}$)

  * **Description:** Represents moderate risk; mothers who received basic care but did not adhere to the current best practices.
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  * **Parameters:** $a=3, b=5, c=8$.
    > $$\mu_{\text{Suff\_ANC}}(x) = \text{trimf}(x; 3, 5, 8)$$

C. Fuzzy Set: **Optimal ANC** ($\mu_{\text{Opt\_ANC}}$)

  * **Description:** Represents the protective factor; mothers who received comprehensive care, leading to the lowest PPD risk associated with this factor.
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=7, b=9, c=12, d=12$.
    > $$\mu_{\text{Opt\_ANC}}(x) = \begin{cases} 0 & \text{if } x \le 7 \\ \frac{x-7}{9-7} & \text{if } 7 < x < 9 \\ 1 & \text{if } x \ge 9 \end{cases}$$

In [ ]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (0 to 12) 
MIN_VISITS = 0.0
MAX_VISITS = 12.0
# Using steps of 0.1 for smooth interpolation
visits_universe = np.arange(MIN_VISITS, MAX_VISITS + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets (based on WHO/Clinical Guidelines)

# A. Inadequate ANC (Trap): Full membership up to 3, 0 at 5
inad_anc_params = [0.0, 3.0, 3.0, 5.0] 

# B. Sufficient ANC (Tri): Starts 3, Peaks 5, Ends 8 (WHO previous standard)
suff_anc_params = [3.0, 5.0, 8.0]

# C. Optimal ANC (Trap): 0 at 7, Full membership from 9 (WHO current standard)
opt_anc_params = [7.0, 9.0, 12.0, 12.0]

# Pre-compute the membership functions (MFs)
inad_anc_mf = fuzz.trapmf(visits_universe, inad_anc_params)
suff_anc_mf = fuzz.trimf(visits_universe, suff_anc_params)
opt_anc_mf = fuzz.trapmf(visits_universe, opt_anc_params)

In [382]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_anc_visits(df: pd.DataFrame, visits_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire anc_visits column."""
    
    # Apply interpolation to the entire column
    mu_inad = [
        fuzz.interp_membership(visits_universe, inad_anc_mf, x)
        for x in df['anc_visits']
    ]
    
    mu_suff = [
        fuzz.interp_membership(visits_universe, suff_anc_mf, x)
        for x in df['anc_visits']
    ]
    
    mu_opt = [
        fuzz.interp_membership(visits_universe, opt_anc_mf, x)
        for x in df['anc_visits']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_anc_inadequate': mu_inad,
        'mu_anc_sufficient': mu_suff,
        'mu_anc_optimal': mu_opt
    })

In [383]:
# Execute Fuzzification and Merge
 
# The code assumes df['anc_visits'] exists in your working DataFrame
fuzzy_df_anc = fuzzify_anc_visits(df, visits_universe)
print(fuzzy_df_anc.shape)

(20000, 3)

In [384]:
#df = pd.concat([df, fuzzy_df_anc], axis=1)
#print(df.shape )

fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_anc], axis=1)
print(fuzzy_df.shape)

(20000, 27)

-------
--------
-----

### **10. gestational_age:**

In [385]:
df["gestational_age"].describe()

count    20000.000000
mean        38.489000
std          2.265598
min         29.000000
25%         37.000000
50%         39.000000
75%         40.000000
max         42.000000
Name: gestational_age, dtype: float64

The variable `gestational_age` is a **continuous numerical variable** ranging from 29 to 42 weeks. We must base the fuzzification on **standard clinical definitions** adopted by the WHO and medical institutions globally.

The standard clinical definition for term pregnancy is the basis for our fuzzification:

  * **Preterm:** $<37$ weeks
  * **Term:** $37$ to $42$ weeks
  * **Post-term:** $\ge 42$ weeks

We will define three fuzzy sets based on the degree of deviation from the **Optimal Term** range, which reflects associated PPD risk (due to neonatal stress/complications):

  * **Preterm GA (High Risk):** Delivery before 37 weeks.
  
  * **Optimal Term GA (Low Risk/Reference):** Delivery between 38 and 41 weeks.
  
  * **Late/Post-term GA (Medium Risk):** Delivery at 37 weeks or 41+ weeks, associated with marginal risk increases.

**Contextual Parameter Setting:**

The fuzzy set boundaries are defined by clinical standards, focusing on the weeks with the lowest complication rates (Optimal Term).

| Fuzzy Set (Weeks) | Clinical Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Preterm GA** | **High Risk:** Associated with neonatal morbidity/mortality and maternal stress. | $\le 36$ | $[29, 38]$ |
| **Optimal Term GA** | **Reference/Low Risk:** Best outcomes, lowest stress. | $[38, 41]$ | $[37, 42]$ |
| **Late/Post-term GA** | **Medium Risk:** Associated with labor induction, fetal distress, or complications. | $\ge 42$ | $[40, 42]$ |

**Note on Overlap:** The **37th week** is the standard boundary. We treat it as the **start of the Optimal Term support** and the **end of the Preterm membership**.

**Detailed Fuzzy Set Definition:**

We use Trapezoidal and Triangular membership functions across the range of 29 to 42 weeks.

A. Fuzzy Set: **Preterm GA** ($\mu_{\text{Preterm}}$)

  * **Description:** Represents high PPD risk due to prematurity complications.
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=29, b=36, c=36, d=38$.
    > $$\mu_{\text{Preterm}}(x) = \begin{cases} 1 & \text{if } x \le 36 \\ \frac{38-x}{38-36} & \text{if } 36 < x < 38 \\ 0 & \text{if } x \ge 38 \end{cases}$$

B. Fuzzy Set: **Optimal Term GA** ($\mu_{\text{Optimal}}$)

  * **Description:** The low-risk reference group, encompassing the ideal delivery window.
  * **Membership Function:** **Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=37, b=38, c=41, d=42$.
    > $$\mu_{\text{Optimal}}(x) = \begin{cases} 0 & \text{if } x \le 37 \text{ or } x \ge 42 \\ \frac{x-37}{38-37} & \text{if } 37 < x < 38 \\ 1 & \text{if } 38 \le x \le 41 \\ \frac{42-x}{42-41} & \text{if } 41 < x < 42 \end{cases}$$

C. Fuzzy Set: **Late/Post-term GA** ($\mu_{\text{Late\_Post}}$)

  * **Description:** Represents medium PPD risk due to potential complications like fetal distress or required induction.
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=40, b=42, c=42, d=42$.
    > $$\mu_{\text{Late\_Post}}(x) = \begin{cases} 0 & \text{if } x \le 40 \\ \frac{x-40}{42-40} & \text{if } 40 < x < 42 \\ 1 & \text{if } x \ge 42 \end{cases}$$

In [386]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (29 to 42 weeks)
MIN_GA = 29.0
MAX_GA = 42.0
ga_universe = np.arange(MIN_GA, MAX_GA + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets (based on Clinical Standards)

# A. Preterm (Trap): Full membership up to 36, 0 at 38
preterm_params = [29.0, 36.0, 36.0, 38.0] 

# B. Optimal Term (Trap): Starts 37, Full membership 38-41, Ends 42
optimal_params = [37.0, 38.0, 41.0, 42.0]

# C. Late/Post-term (Trap): 0 at 40, Full membership from 42
late_post_params = [40.0, 42.0, 42.0, 42.0]

# Pre-compute the membership functions (MFs) ---
preterm_mf = fuzz.trapmf(ga_universe, preterm_params)
optimal_mf = fuzz.trapmf(ga_universe, optimal_params)
late_post_mf = fuzz.trapmf(ga_universe, late_post_params)

In [387]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_gestational_age(df: pd.DataFrame, ga_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire gestational_age column."""
    
    # Apply interpolation to the entire column
    mu_preterm = [
        fuzz.interp_membership(ga_universe, preterm_mf, x)
        for x in df['gestational_age']
    ]
    
    mu_optimal = [
        fuzz.interp_membership(ga_universe, optimal_mf, x)
        for x in df['gestational_age']
    ]
    
    mu_late_post = [
        fuzz.interp_membership(ga_universe, late_post_mf, x)
        for x in df['gestational_age']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_ga_preterm': mu_preterm,
        'mu_ga_optimal': mu_optimal,
        'mu_ga_late_post': mu_late_post
    })

In [388]:
# Execute Fuzzification and Merge
 
fuzzy_df_ga = fuzzify_gestational_age(df, ga_universe)
print(fuzzy_df_ga.shape)

(20000, 3)

In [ ]:
#df = pd.concat([df, fuzzy_df_ga], axis=1)
#print(df.shape)

In [389]:
fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_ga], axis=1)
print(fuzzy_df.shape)

(20000, 30)

---------------
---------------
-------------------

### **11. maternal_age_at_first_birth:**

In [390]:
df["maternal_age_at_first_birth"].describe()

count    20000.000000
mean        21.566200
std          4.697619
min         15.000000
25%         19.000000
50%         21.000000
75%         23.000000
max         44.000000
Name: maternal_age_at_first_birth, dtype: float64

The risk for PPD is generally elevated at the two extremes of the reproductive age spectrum: **adolescent/early motherhood** and **advanced maternal age**.

The variable `maternal_age_at_first_birth` ranges from 15 to 44 years. We will use Trapezoidal membership functions based on standard clinical cutoffs.

We define three fuzzy sets based on clinical risk profiles:

  * **Early Motherhood Risk (High Risk):** Age at first birth $<20$ years (Adolescent/Early motherhood, associated with high social/economic stress and poor outcomes).
  * **Optimal Age (Low Risk/Reference):** Age at first birth $21-34$ years (The low-risk reference group, optimal demographic window).
  * **Advanced Age Risk (Medium Risk):** Age at first birth $\ge 35$ years (Advanced maternal age, associated with higher medical risk and anxiety).

The fuzzy set boundaries are defined by internationally and locally accepted demographic standards:

| Fuzzy Set (Age) | Clinical Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Early Motherhood** | **High Risk:** Starts below the legal/demographic optimal age. | $\le 19$ | $[15, 22]$ |
| **Optimal Age** | **Low Risk/Reference:** The ideal childbearing years. | $[21, 33]$ | $[20, 35]$ |
| **Advanced Age** | **Medium Risk:** Advanced maternal age threshold. | $\ge 35$ | $[34, 44]$ |


We use Trapezoidal membership functions across the range of 15 to 44 years.

A. Fuzzy Set: **Early Motherhood Risk** ($\mu_{\text{Early\_M}}$)

  * **Description:** Captures the high risk associated with adolescent and very early motherhood.
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=15, b=19, c=19, d=22$.

B. Fuzzy Set: **Optimal Age** ($\mu_{\text{Optimal\_Age}}$)

  * **Description:** The primary protective/reference group.
  * **Membership Function:** **Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=20, b=21, c=33, d=35$.

C. Fuzzy Set: **Advanced Age Risk** ($\mu_{\text{Advanced\_A}}$)

  * **Description:** Represents the increased stress and medical risk associated with advanced maternal age.
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=34, b=35, c=44, d=44$.

In [391]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (15 to 44 years)
MIN_AGE = 15.0
MAX_AGE = 44.0
age_universe = np.arange(MIN_AGE, MAX_AGE + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets (based on Clinical Standards) ---

# A. Early Motherhood (Trap): Full membership up to 19, 0 at 22
early_m_params = [15.0, 19.0, 19.0, 22.0] 

# B. Optimal Age (Trap): Starts 20, Full membership 21-33, Ends 35
optimal_age_params = [20.0, 21.0, 33.0, 35.0]

# C. Advanced Age (Trap): 0 at 34, Full membership from 35
advanced_a_params = [34.0, 35.0, 44.0, 44.0]

# Pre-compute the membership functions (MFs): 
early_m_mf = fuzz.trapmf(age_universe, early_m_params)
optimal_age_mf = fuzz.trapmf(age_universe, optimal_age_params)
advanced_a_mf = fuzz.trapmf(age_universe, advanced_a_params)

In [392]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_maternal_age_at_first_birth(df: pd.DataFrame, age_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire maternal_age_at_first_birth column."""
    
    # Apply interpolation to the entire column
    mu_early = [
        fuzz.interp_membership(age_universe, early_m_mf, x)
        for x in df['maternal_age_at_first_birth']
    ]
    
    mu_optimal = [
        fuzz.interp_membership(age_universe, optimal_age_mf, x)
        for x in df['maternal_age_at_first_birth']
    ]
    
    mu_advanced = [
        fuzz.interp_membership(age_universe, advanced_a_mf, x)
        for x in df['maternal_age_at_first_birth']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_maternal_age_early': mu_early,
        'mu_maternal_age_optimal': mu_optimal,
        'mu_maternal_age_advanced': mu_advanced
    })

In [393]:
# Execute Fuzzification and Merge:

fuzzy_df_age = fuzzify_maternal_age_at_first_birth(df, age_universe)
print(fuzzy_df_age.shape)

(20000, 3)

In [ ]:
#df = pd.concat([df, fuzzy_df_age], axis=1)
#print(df.shape)

In [394]:
fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_age], axis=1)
print(fuzzy_df.shape)

(20000, 33)

-------------
---------------
-------------

### **12. partner_support_score:**

In [395]:
df["partner_support_score"].describe()

count    20000.000000
mean         6.593150
std          2.115375
min          0.000000
25%          5.100000
50%          6.700000
75%          8.200000
max         10.000000
Name: partner_support_score, dtype: float64

The score is a continuous numerical variable (0 to 10). We structure the fuzzy sets to reflect the **inverse relationship** between the score and PPD risk.

We will define three fuzzy sets based on the degree of protective support:

  * **Low Support (High Risk):** Scores indicating severe lack of emotional and practical support.

  * **Moderate Support (Medium Risk):** Scores around the median, reflecting adequate but imperfect support.
  
  * **High Support (Low Risk/Reference):** Scores indicating excellent, reliable support, acting as a strong protective buffer.

We set the boundaries based on the clinical understanding that a score close to 0 represents a severe vulnerability (high risk), while a score near 10 represents maximum protection (low risk). 

| Fuzzy Set (Score) | Clinical Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Low Support** | **High Risk:** Little or no support; a major PPD predictor. | $\le 4$ | $[0, 6]$ |
| **Moderate Support** | **Medium Risk:** Adequate support, but still prone to vulnerability during crises (centered near median $\approx 6.7$). | $6$ | $[4, 8]$ |
| **High Support** | **Low Risk/Protective:** Excellent support, acting as a strong buffer. | $\ge 9$ | $[7, 10]$ |

We use Trapezoidal and Triangular membership functions across the range of 0 to 10.

A. Fuzzy Set: **Low Support** ($\mu_{\text{Low\_S}}$)

  * **Description:** Represents high PPD risk due to severe lack of partner support.
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=0, b=4, c=4, d=6$.
    > $$\mu_{\text{Low\_S}}(x) = \begin{cases} 1 & \text{if } x \le 4 \\ \frac{6-x}{6-4} & \text{if } 4 < x < 6 \\ 0 & \text{if } x \ge 6 \end{cases}$$

B. Fuzzy Set: **Moderate Support** ($\mu_{\text{Mod\_S}}$)

  * **Description:** Represents medium risk; the support is present but may be insufficient or inconsistent. Centered at 6.
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  * **Parameters:** $a=4, b=6, c=8$.
    > $$\mu_{\text{Mod\_S}}(x) = \text{trimf}(x; 4, 6, 8)$$

C. Fuzzy Set: **High Support** ($\mu_{\text{High\_S}}$)

  * **Description:** Represents the protective, low-risk group with reliable and strong emotional/practical support.
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=7, b=9, c=10, d=10$.
    > $$\mu_{\text{High\_S}}(x) = \begin{cases} 0 & \text{if } x \le 7 \\ \frac{x-7}{9-7} & \text{if } 7 < x < 9 \\ 1 & \text{if } x \ge 9 \end{cases}$$

In [396]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (0 to 10)
MIN_SCORE = 0.0
MAX_SCORE = 10.0
score_universe = np.arange(MIN_SCORE, MAX_SCORE + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets

# A. Low Support (Trap): Full membership up to 4, 0 at 6
low_s_params = [0.0, 4.0, 4.0, 6.0] 

# B. Moderate Support (Tri): Starts 4, Peaks 6, Ends 8
mod_s_params = [4.0, 6.0, 8.0]

# C. High Support (Trap): 0 at 7, Full membership from 9
high_s_params = [7.0, 9.0, 10.0, 10.0]

# Pre-compute the membership functions (MFs)
low_s_mf = fuzz.trapmf(score_universe, low_s_params)
mod_s_mf = fuzz.trimf(score_universe, mod_s_params)
high_s_mf = fuzz.trapmf(score_universe, high_s_params)

In [397]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_partner_support(df: pd.DataFrame, score_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire partner_support_score column."""
    
    # Apply interpolation to the entire column
    mu_low = [
        fuzz.interp_membership(score_universe, low_s_mf, x)
        for x in df['partner_support_score']
    ]
    
    mu_mod = [
        fuzz.interp_membership(score_universe, mod_s_mf, x)
        for x in df['partner_support_score']
    ]
    
    mu_high = [
        fuzz.interp_membership(score_universe, high_s_mf, x)
        for x in df['partner_support_score']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_support_low': mu_low,
        'mu_support_mod': mu_mod,
        'mu_support_high': mu_high
    })

In [398]:
# Execute Fuzzification and Merge

fuzzy_df_support = fuzzify_partner_support(df, score_universe)
print(fuzzy_df_support.shape)

#df = pd.concat([df, fuzzy_df_support], axis=1)
#print(df.shape)
 
fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_support], axis=1)
print(fuzzy_df.shape)

(20000, 3)
(20000, 36)

---------------
------
-----

### **13. family_support_score:**

In [399]:
df["family_support_score"].describe()

count    20000.000000
mean         6.209595
std          2.220976
min          0.000000
25%          4.600000
50%          6.200000
75%          7.800000
max         10.000000
Name: family_support_score, dtype: float64

**Family Support Score** (a score from 0 to 10) is consistently identified in research from Nepal and globally as one of the most significant **social determinants** and **protective buffers** against maternal mental health issues, including PPD. The findings show that inadequate support from family/relatives is a major risk factor (Source 1.1, 1.5, 1.7, 2.5).

The fuzzification must reflect the clinical finding that **lack of support** (low score) is a **major vulnerability (High Risk)**, while **strong support** (high score) is a **significant protective factor (Low Risk)**.

The variable `family_support_score` is a continuous numerical variable (0 to 10), with a mean and median centered around 6.2. We use this distribution alongside clinical standards to define the fuzzy sets.

We define three fuzzy sets based on the degree of psychological protection offered by the family unit:

  * **Inadequate Support (High Risk):** Scores indicating severe lack of support, a high vulnerability factor.
  * **Moderate Support (Medium Risk/Transition):** Scores around the dataset's mean/median, suggesting neither a strong risk nor a strong buffer.
  * **Strong Support (Low Risk/Protective):** Scores indicating reliable and comprehensive family support.

The boundaries are set based on the score range, using a slight skew to prioritize the distinction between protective and high-risk levels.

| Fuzzy Set (Score) | Clinical Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Inadequate Support** | **High Risk:** Scores far below the median, indicating a critical social deficit. | $\le 4$ | $[0, 6]$ |
| **Moderate Support** | **Medium Risk:** Around the data's mean ($\approx 6.2$); typical support levels, not fully protective. | $6$ | $[4, 8]$ |
| **Strong Support** | **Low Risk/Protective:** Scores indicating strong family cohesion and instrumental support. | $\ge 9$ | $[7, 10]$ |

We use Trapezoidal and Triangular membership functions across the range of 0 to 10.

A. Fuzzy Set: **Inadequate Support** ($\mu_{\text{Inad\_F}}$)

  * **Description:** Represents high PPD risk due to emotional and instrumental isolation.
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=0, b=4, c=4, d=6$.
    > $$\mu_{\text{Inad\_F}}(x) = \begin{cases} 1 & \text{if } x \le 4 \\ \frac{6-x}{6-4} & \text{if } 4 < x < 6 \\ 0 & \text{if } x \ge 6 \end{cases}$$

B. Fuzzy Set: **Moderate Support** ($\mu_{\text{Mod\_F}}$)

  * **Description:** Represents medium risk; adequate but not exceptional support.
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  * **Parameters:** $a=4, b=6, c=8$.
    > $$\mu_{\text{Mod\_F}}(x) = \text{trimf}(x; 4, 6, 8)$$

C. Fuzzy Set: **Strong Support** ($\mu_{\text{Strong\_F}}$)

  * **Description:** Represents the low-risk, protective group with high family resources.
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=7, b=9, c=10, d=10$.
    > $$\mu_{\text{Strong\_F}}(x) = \begin{cases} 0 & \text{if } x \le 7 \\ \frac{x-7}{9-7} & \text{if } 7 < x < 9 \\ 1 & \text{if } x \ge 9 \end{cases}$$

In [400]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (0 to 10)
MIN_SCORE = 0.0
MAX_SCORE = 10.0
score_universe = np.arange(MIN_SCORE, MAX_SCORE + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets

# A. Inadequate Support (Trap): Full membership up to 4, 0 at 6
inad_f_params = [0.0, 4.0, 4.0, 6.0] 

# B. Moderate Support (Tri): Starts 4, Peaks 6, Ends 8
mod_f_params = [4.0, 6.0, 8.0]

# C. Strong Support (Trap): 0 at 7, Full membership from 9
strong_f_params = [7.0, 9.0, 10.0, 10.0]

# Pre-compute the membership functions (MFs)
inad_f_mf = fuzz.trapmf(score_universe, inad_f_params)
mod_f_mf = fuzz.trimf(score_universe, mod_f_params)
strong_f_mf = fuzz.trapmf(score_universe, strong_f_params)

In [401]:
# Fuzzification Function (Applied to the entire column) ---

def fuzzify_family_support(df: pd.DataFrame, score_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire family_support_score column."""
    
    # Apply interpolation to the entire column
    mu_inad = [
        fuzz.interp_membership(score_universe, inad_f_mf, x)
        for x in df['family_support_score']
    ]
    
    mu_mod = [
        fuzz.interp_membership(score_universe, mod_f_mf, x)
        for x in df['family_support_score']
    ]
    
    mu_strong = [
        fuzz.interp_membership(score_universe, strong_f_mf, x)
        for x in df['family_support_score']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_family_inadequate': mu_inad,
        'mu_family_moderate': mu_mod,
        'mu_family_strong': mu_strong
    })

In [402]:
# Execute Fuzzification and Merge

fuzzy_df_family = fuzzify_family_support(df, score_universe)
print(fuzzy_df_family.shape)

#df = pd.concat([df, fuzzy_df_family], axis=1)
#print(df.shape)

fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_family], axis=1)
print(fuzzy_df.shape)

(20000, 3)
(20000, 39)

---------------
------------
-----------

### **14. domestic_violence_exposure:**

In [403]:
df["domestic_violence_exposure"].value_counts()

domestic_violence_exposure
Never        12696
Rarely        3613
Sometimes     2745
Often          946
Name: count, dtype: int64

**Exposure to Domestic Violence (DV)** is a severe psychosocial stressor.

The variable `domestic_violence_exposure` is an **ordinal categorical variable** with four levels. The risk of PPD is directly correlated with the frequency and severity of the exposure.

We will define three fuzzy sets based on the degree of PPD risk, prioritizing the clinical and psychosocial literature which confirms that **any exposure to DV is a serious risk factor**.

**Membership Functions and Fuzzy Sets:**

**Input Feature:** `domestic_violence_exposure` (Ordinal Categorical)
**Fuzzy Sets (Output Features):**

1.  **High DV Risk** ($\mu_{\text{dv\_high\_risk}}$): Associated with 'Often' and 'Sometimes' exposure.
2.  **Moderate DV Risk** ($\mu_{\text{dv\_mod\_risk}}$): Associated with 'Rarely' exposure, representing a significant but infrequent stressor.
3.  **No DV Risk** ($\mu_{\text{dv\_no\_risk}}$): Associated with 'Never' exposure, serving as the protective reference group.

| Crisp Input Category (x) | PPD Risk Rationale (Clinical Context) | $\mu_{\text{dv\_high\_risk}}$ | $\mu_{\text{dv\_mod\_risk}}$ | $\mu_{\text{dv\_no\_risk}}$ |
| :--- | :--- | :--- | :--- | :--- |
| **Often** | **Full Risk:** Chronic, severe, overwhelming stress. | **1.0** | 0.0 | 0.0 |
| **Sometimes** | **Very High Risk:** Frequent stress, high emotional toll. | **0.9** | **0.1** | 0.0 |
| **Rarely** | **Moderate Risk:** Even rare exposure is a critical vulnerability factor. | **0.3** | **0.7** | 0.0 |
| **Never** | **Protective:** Absence of this major stressor. | 0.0 | 0.0 | **1.0** |

  * **Rationale for Overlap:** The membership values reflect the clinical standard that *any* exposure (Rarely, Sometimes, Often) immediately places the mother in a risk category (High or Moderate DV Risk), unlike some other factors where 'Rarely' might be closer to 'Never'.

A. Fuzzy Set: **High DV Risk** ($\mu_{\text{dv\_high\_risk}}$)

  * **Description:** Represents severe, chronic PPD risk due to frequent or continuous violence.
  * **Membership Function (Lookup):**
    > $$\mu_{\text{dv\_high\_risk}}(x) = \begin{cases} 1.0 & \text{if } x = \text{'Often'} \\ 0.9 & \text{if } x = \text{'Sometimes'} \\ 0.3 & \text{if } x = \text{'Rarely'} \\ 0.0 & \text{if } x = \text{'Never'} \end{cases}$$

B. Fuzzy Set: **Moderate DV Risk** ($\mu_{\text{dv\_mod\_risk}}$)

  * **Description:** Captures the intermediate but still significant risk associated with infrequent exposure.
  * **Membership Function (Lookup):**
    > $$\mu_{\text{dv\_mod\_risk}}(x) = \begin{cases} 0.0 & \text{if } x = \text{'Often'} \\ 0.1 & \text{if } x = \text{'Sometimes'} \\ 0.7 & \text{if } x = \text{'Rarely'} \\ 0.0 & \text{if } x = \text{'Never'} \end{cases}$$

C. Fuzzy Set: **No DV Risk** ($\mu_{\text{dv\_no\_risk}}$)

  * **Description:** Represents the protective reference group (absence of this acute stressor).
  * **Membership Function (Lookup):**
    > $$\mu_{\text{dv\_no\_risk}}(x) = \begin{cases} 0.0 & \text{if } x \in \{\text{'Often'}, \text{'Sometimes'}, \text{'Rarely'}\} \\ 1.0 & \text{if } x = \text{'Never'} \end{cases}$$

In [404]:
import numpy as np
import pandas as pd

# Define the Discrete Fuzzification Map: 

fuzzy_map_dv = {
    'Often':       {'mu_dv_high_risk': 1.0, 'mu_dv_mod_risk': 0.0, 'mu_dv_no_risk': 0.0},
    'Sometimes':   {'mu_dv_high_risk': 0.9, 'mu_dv_mod_risk': 0.1, 'mu_dv_no_risk': 0.0},
    'Rarely':      {'mu_dv_high_risk': 0.3, 'mu_dv_mod_risk': 0.7, 'mu_dv_no_risk': 0.0},
    'Never':       {'mu_dv_high_risk': 0.0, 'mu_dv_mod_risk': 0.0, 'mu_dv_no_risk': 1.0},
}

# Fuzzification Function: 

def fuzzify_categorical_level(df: pd.DataFrame, input_column: str, mapping: dict) -> pd.DataFrame:
    """
    Applies the discrete fuzzy mapping to a categorical column.
    """
    
    # Extract the fuzzy set names from the first category's mapping keys
    first_key = list(mapping.keys())[0]
    fuzzy_set_names = list(mapping[first_key].keys())
    
    fuzzy_features = {}
    
    for name in fuzzy_set_names:
        # Use pandas map for efficiency
        fuzzy_features[name] = df[input_column].map(lambda x: mapping[x][name])

    return pd.DataFrame(fuzzy_features)

In [405]:
## Execute Fuzzification

fuzzy_df_dv = fuzzify_categorical_level(df, 'domestic_violence_exposure', fuzzy_map_dv)
fuzzy_df_dv.shape

(20000, 3)

In [ ]:
# Concatenate the new fuzzy features back to the original DataFrame
#df = pd.concat([df, fuzzy_df_dv], axis=1)
#df.shape

(20000, 62)

In [406]:
fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_dv], axis=1)
fuzzy_df.shape

(20000, 42)

-----
-----
-----

### **15. social_isolation_score:**

In [407]:
df["social_isolation_score"].describe()

count    20000.000000
mean         4.569215
std          2.130144
min          0.000000
25%          3.000000
50%          4.400000
75%          6.000000
max         10.000000
Name: social_isolation_score, dtype: float64

The **Social Isolation Score** (ranging from 0 to 10) is a direct measure of a mother's perceived lack of social integration and support. **Higher scores indicate greater isolation** and thus, a **higher risk for PPD**.

The variable `social_isolation_score` is a continuous numerical variable (0 to 10), with higher scores corresponding to higher PPD risk. We will structure the fuzzy sets based on the degree of isolation's clinical impact.

We define three fuzzy sets based on the degree of social vulnerability:

  * **Low Isolation (Low Risk/Reference):** Scores indicating good social ties and integration.
  
  * **Moderate Isolation (Medium Risk/Transition):** Scores around the mean/median, suggesting occasional loneliness but not critical isolation.
  
  * **High Isolation (High Risk):** Scores indicating severe, detrimental lack of social connection, a major PPD vulnerability factor.

The boundaries are set to clearly distinguish between a healthy social environment and a critically isolated one.

| Fuzzy Set (Score) | Clinical Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Low Isolation** | **Low Risk/Protective:** Strong social network. | $\le 2$ | $[0, 4]$ |
| **Moderate Isolation** | **Medium Risk:** Occasional feelings of loneliness; manageable. (Centered near median $\approx 4.4$). | $4.5$ | $[3, 7]$ |
| **High Isolation** | **High Risk:** Severe and persistent isolation; a major, acute PPD predictor. | $\ge 8$ | $[6, 10]$ |

We use Trapezoidal and Triangular membership functions across the range of 0 to 10.

A. Fuzzy Set: **Low Isolation** ($\mu_{\text{Low\_Iso}}$)

  * **Description:** Represents low PPD risk due to strong social capital and integration.
  
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters:** $a=0, b=2, c=2, d=4$.
    > $$\mu_{\text{Low\_Iso}}(x) = \begin{cases} 1 & \text{if } x \le 2 \\ \frac{4-x}{4-2} & \text{if } 2 < x < 4 \\ 0 & \text{if } x \ge 4 \end{cases}$$

B. Fuzzy Set: **Moderate Isolation** ($\mu_{\text{Mod\_Iso}}$)

  * **Description:** Represents medium risk; the transitional group where isolation is noticeable but not chronic.
  
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  
  * **Parameters:** $a=3, b=4.5, c=7$.
    > $$\mu_{\text{Mod\_Iso}}(x) = \text{trimf}(x; 3, 4.5, 7)$$

C. Fuzzy Set: **High Isolation** ($\mu_{\text{High\_Iso}}$)

  * **Description:** Represents high PPD risk; chronic, severe social detachment.
  
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters:** $a=6, b=8, c=10, d=10$.
    > $$\mu_{\text{High\_Iso}}(x) = \begin{cases} 0 & \text{if } x \le 6 \\ \frac{x-6}{8-6} & \text{if } 6 < x < 8 \\ 1 & \text{if } x \ge 8 \end{cases}$$

In [408]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (0 to 10)
MIN_SCORE = 0.0
MAX_SCORE = 10.0
score_universe = np.arange(MIN_SCORE, MAX_SCORE + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets

# A. Low Isolation (Trap): Full membership up to 2, 0 at 4
low_iso_params = [0.0, 2.0, 2.0, 4.0] 

# B. Moderate Isolation (Tri): Starts 3, Peaks 4.5, Ends 7
mod_iso_params = [3.0, 4.5, 7.0]

# C. High Isolation (Trap): 0 at 6, Full membership from 8
high_iso_params = [6.0, 8.0, 10.0, 10.0]

# Pre-compute the membership functions (MFs)
low_iso_mf = fuzz.trapmf(score_universe, low_iso_params)
mod_iso_mf = fuzz.trimf(score_universe, mod_iso_params)
high_iso_mf = fuzz.trapmf(score_universe, high_iso_params)

In [409]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_social_isolation(df: pd.DataFrame, score_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire social_isolation_score column."""
    
    # Apply interpolation to the entire column
    mu_low = [
        fuzz.interp_membership(score_universe, low_iso_mf, x)
        for x in df['social_isolation_score']
    ]
    
    mu_mod = [
        fuzz.interp_membership(score_universe, mod_iso_mf, x)
        for x in df['social_isolation_score']
    ]
    
    mu_high = [
        fuzz.interp_membership(score_universe, high_iso_mf, x)
        for x in df['social_isolation_score']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_isolation_low': mu_low,
        'mu_isolation_mod': mu_mod,
        'mu_isolation_high': mu_high
    })

In [410]:
# Execute Fuzzification and Merge:

fuzzy_df_isolation = fuzzify_social_isolation(df, score_universe)
print(fuzzy_df_isolation.shape)

#df = pd.concat([df, fuzzy_df_isolation], axis=1)
#print(df.shape)

fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_isolation], axis=1)
print(fuzzy_df.shape)

(20000, 3)
(20000, 45)

----------
-----------
----------

### **16. sleep_quality:**

In [411]:
df["sleep_quality"].describe()

count    20000.000000
mean         6.659985
std          1.691710
min          1.000000
25%          5.500000
50%          6.700000
75%          7.900000
max         10.000000
Name: sleep_quality, dtype: float64

**Sleep Quality** is one of a direct and crucial biological factors influencing maternal mental health. **Poor sleep quality (low score) is a major precipitating factor for PPD**, while good sleep (high score) is a protective factor.

The variable `sleep_quality` is a continuous numerical variable (1 to 10), with **lower scores corresponding to higher PPD risk**. We structure the fuzzy sets to reflect this inverse relationship.

**We define three fuzzy sets based on the degree of sleep-related PPD risk:**

  * **Poor Sleep (High Risk):** Scores indicating significant sleep disturbance/insomnia.
  
  * **Moderate Sleep (Medium Risk/Transition):** Scores around the dataset's mean/median, suggesting adequate but not perfect sleep.
  
  * **Good Sleep (Low Risk/Protective):** Scores indicating highly restorative and sufficient sleep.

**Contextual Parameter Setting:**

The boundaries are set to reflect clinically significant thresholds for sleep quality, prioritizing the distinction between functionally poor and functionally good sleep.

| Fuzzy Set (Score) | Clinical Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Poor Sleep** | **High Risk:** Sleep quality is often rated $\le 5$ in cases of clinical insomnia/severe fatigue. | $\le 4$ | $[1, 6]$ |
| **Moderate Sleep** | **Medium Risk:** Adequate sleep, but still vulnerable to fragmentation/stress. (Centered near median $\approx 6.7$). | $6.5$ | $[4, 8]$ |
| **Good Sleep** | **Low Risk/Protective:** High sleep quality, acting as a strong mental health buffer. | $\ge 9$ | $[7, 10]$ |

We use Trapezoidal and Triangular membership functions across the range of 1 to 10.

A. Fuzzy Set: **Poor Sleep** ($\mu_{\text{Poor\_S}}$)

  * **Description:** Represents high PPD risk due to sleep deprivation and disturbance.
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=1, b=4, c=4, d=6$.

B. Fuzzy Set: **Moderate Sleep** ($\mu_{\text{Mod\_S}}$)

  * **Description:** Represents medium risk; the transitional group with satisfactory but improvable sleep.
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  * **Parameters:** $a=4, b=6.5, c=8$.

C. Fuzzy Set: **Good Sleep** ($\mu_{\text{Good\_S}}$)

  * **Description:** Represents the protective, low-risk group with excellent, restorative sleep.
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  * **Parameters:** $a=7, b=9, c=10, d=10$.

In [412]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (1 to 10) 
MIN_SCORE = 1.0
MAX_SCORE = 10.0
score_universe = np.arange(MIN_SCORE, MAX_SCORE + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets

# A. Poor Sleep (Trap): Full membership up to 4, 0 at 6
poor_s_params = [1.0, 4.0, 4.0, 6.0] 

# B. Moderate Sleep (Tri): Starts 4, Peaks 6.5, Ends 8
mod_s_params = [4.0, 6.5, 8.0]

# C. Good Sleep (Trap): 0 at 7, Full membership from 9
good_s_params = [7.0, 9.0, 10.0, 10.0]

# Pre-compute the membership functions (MFs)
poor_s_mf = fuzz.trapmf(score_universe, poor_s_params)
mod_s_mf = fuzz.trimf(score_universe, mod_s_params)
good_s_mf = fuzz.trapmf(score_universe, good_s_params)

In [413]:
# Fuzzification Function (Applied to the entire column): 

def fuzzify_sleep_quality(df: pd.DataFrame, score_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire sleep_quality column."""
    
    # Apply interpolation to the entire column
    mu_poor = [
        fuzz.interp_membership(score_universe, poor_s_mf, x)
        for x in df['sleep_quality']
    ]
    
    mu_mod = [
        fuzz.interp_membership(score_universe, mod_s_mf, x)
        for x in df['sleep_quality']
    ]
    
    mu_good = [
        fuzz.interp_membership(score_universe, good_s_mf, x)
        for x in df['sleep_quality']
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_sleep_poor': mu_poor,
        'mu_sleep_moderate': mu_mod,
        'mu_sleep_good': mu_good
    })

In [414]:
# Execute Fuzzification and Merge

fuzzy_df_sleep = fuzzify_sleep_quality(df, score_universe)
print(fuzzy_df_sleep.shape)

#df = pd.concat([df, fuzzy_df_sleep], axis=1)
#print(df.shape)

fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_sleep], axis=1)
print(fuzzy_df.shape)

(20000, 3)
(20000, 48)

--------------
-------------
-------

### **17. stressful_life_events:**

In [415]:
df["stressful_life_events"].describe()

count    20000.000000
mean         1.083450
std          1.074916
min          0.000000
25%          0.000000
50%          1.000000
75%          2.000000
max          5.000000
Name: stressful_life_events, dtype: float64

The **Stressful Life Events** score (ranging from 0 to 5, representing a count of recent major stressors) is one of the most consistently identified **risk factors** for Postpartum Depression (PPD). **Higher scores indicate a higher cumulative psychological burden** and therefore, a **higher risk for PPD**.

The variable `stressful_life_events` is a discrete count (0 to 5), with higher counts corresponding to higher PPD risk. We will structure the fuzzy sets based on the magnitude of the cumulative stress load.

We define three fuzzy sets based on the degree of stress vulnerability:

  * **Low Stress Load (Low Risk/Reference):** Zero to one recent major event.
  
  * **Moderate Stress Load (Medium Risk/Transition):** Two to three recent major events.
  
  * **High Stress Load (High Risk):** Four or more recent major events.

The boundaries are set based on the clinical severity, where cumulative stress becomes clinically significant beyond 1 or 2 events.

| Fuzzy Set (Count) | Clinical Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Low Stress Load** | **Low Risk:** Minimal or no major recent stressors. | $\le 0$ | $[0, 1.5]$ |
| **Moderate Stress Load** | **Medium Risk:** Two to three major events; manageable but requires coping. (Centered near median $\approx 1$). | $2$ | $[0.5, 3.5]$ |
| **High Stress Load** | **High Risk:** Four or more events; overwhelming cumulative burden, a major PPD predictor. | $\ge 4$ | $[3, 5]$ |

We use Trapezoidal and Triangular membership functions across the range of 0 to 5.

A. Fuzzy Set: **Low Stress Load** ($\mu_{\text{Low\_SL}}$)

  * **Description:** Represents low PPD risk due to a low number of recent stressors.
  
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters:** $a=0, b=0, c=0, d=1.5$.
    > $$\mu_{\text{Low\_SL}}(x) = \begin{cases} 1 & \text{if } x = 0 \\ \frac{1.5-x}{1.5-0} & \text{if } 0 < x < 1.5 \\ 0 & \text{if } x \ge 1.5 \end{cases}$$

B. Fuzzy Set: **Moderate Stress Load** ($\mu_{\text{Mod\_SL}}$)

  * **Description:** Represents medium risk; the transitional group balancing low and high risk.
  
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  
  * **Parameters:** $a=0.5, b=2, c=3.5$.
    > $$\mu_{\text{Mod\_SL}}(x) = \text{trimf}(x; 0.5, 2, 3.5)$$

C. Fuzzy Set: **High Stress Load** ($\mu_{\text{High\_SL}}$)

  * **Description:** Represents high PPD risk due to severe, cumulative stress.
  \
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters:** $a=3, b=4, c=5, d=5$.
    > $$\mu_{\text{High\_SL}}(x) = \begin{cases} 0 & \text{if } x \le 3 \\ \frac{x-3}{4-3} & \text{if } 3 < x < 4 \\ 1 & \text{if } x \ge 4 \end{cases}$$

In [416]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (0 to 5)
MIN_SCORE = 0.0
MAX_SCORE = 5.0
score_universe = np.arange(MIN_SCORE, MAX_SCORE + 0.1, 0.1) 

# Define the Contextual Parameters for Fuzzy Sets

# A. Low Stress Load (Trap): Full membership at 0, 0 at 1.5
low_sl_params = [0.0, 0.0, 0.0, 1.5] 

# B. Moderate Stress Load (Tri): Starts 0.5, Peaks 2, Ends 3.5
mod_sl_params = [0.5, 2.0, 3.5]

# C. High Stress Load (Trap): 0 at 3, Full membership from 4
high_sl_params = [3.0, 4.0, 5.0, 5.0]

# Pre-compute the membership functions (MFs)
low_sl_mf = fuzz.trapmf(score_universe, low_sl_params)
mod_sl_mf = fuzz.trimf(score_universe, mod_sl_params)
high_sl_mf = fuzz.trapmf(score_universe, high_sl_params)

In [417]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_stressful_life_events(df: pd.DataFrame, score_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire stressful_life_events column."""
    
    # Ensure input data is treated as continuous/float for fuzzy calculations
    input_data = df['stressful_life_events'].astype(float)
    
    # Apply interpolation to the entire column
    mu_low = [
        fuzz.interp_membership(score_universe, low_sl_mf, x)
        for x in input_data
    ]
    
    mu_mod = [
        fuzz.interp_membership(score_universe, mod_sl_mf, x)
        for x in input_data
    ]
    
    mu_high = [
        fuzz.interp_membership(score_universe, high_sl_mf, x)
        for x in input_data
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_stress_low': mu_low,
        'mu_stress_mod': mu_mod,
        'mu_stress_high': mu_high
    })

In [418]:
# Execute Fuzzification and Merge:

fuzzy_df_events = fuzzify_stressful_life_events(df, score_universe)
print(fuzzy_df_events.shape)

#df = pd.concat([df, fuzzy_df_events], axis=1)
#print(df.shape)

fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_events], axis=1)
print(fuzzy_df.shape)

(20000, 3)
(20000, 51)

-------------
----------
-----------------

### **18. distance_to_health_facility:**

In [419]:
df["distance_to_health_facility"].describe()

count    20000.000000
mean         4.606329
std          5.815983
min          0.500000
25%          1.200000
50%          2.620000
75%          5.630000
max         50.000000
Name: distance_to_health_facility, dtype: float64

**Distance to Health Facility** (measured in kilometers) is a major determinant of **access to care** (ANC, delivery, and postpartum follow-up) and is therefore an **inverse risk factor** for PPD. **Greater distance (higher score) leads to higher PPD risk** due to poor service utilization and increased stress regarding emergencies.

The fuzzification must reflect the reality of infrastructure in many parts of Nepal, where accessibility greatly impacts maternal health outcomes.

The variable `distance_to_health_facility` is a continuous numerical variable (ranging from 0.5 to 50 km). We structure the fuzzy sets based on the clinical understanding of access barriers.

We define three fuzzy sets based on the degree of accessibility (and corresponding PPD risk):

  * **Easy Access (Low Risk/Reference):** Very short distance, allowing for timely and frequent use (core near 1-2 km).
  
  * **Moderate Access (Medium Risk/Transition):** Moderate distance, representing a manageable but significant barrier (core near 5-6 km).
  
  * **Difficult Access (High Risk):** Long distance, representing a severe barrier to critical care, associated with high risk (core $\ge 15$ km).

We set the boundaries based on standard public health classifications for access:

| Fuzzy Set (Distance - km) | Clinical Rationale (PPD Risk) | Core (Full $\mu=1$) | Support Range (Start to End) |
| :--- | :--- | :--- | :--- |
| **Easy Access** | **Low Risk:** Access within the community; can walk or reach quickly (Q1 $\approx 1.2$ km). | $\le 2$ | $[0.5, 5]$ |
| **Moderate Access** | **Medium Risk:** Requires transport; manageable but delays possible (Median $\approx 2.6$ km). | $6$ | $[3, 10]$ |
| **Difficult Access** | **High Risk:** Severe geographical barrier; delays often critical; high stress (Q3 $\approx 5.6$ km, max=50). | $\ge 15$ | $[8, 50]$ |

We use Trapezoidal and Triangular membership functions across the range of 0.5 to 50 km.

A. Fuzzy Set: **Easy Access** ($\mu_{\text{Easy\_A}}$)

  * **Description:** Represents low PPD risk due to high accessibility and low stress regarding emergencies.
  
  * **Membership Function:** **Left-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters:** $a=0.5, b=2, c=2, d=5$.

B. Fuzzy Set: **Moderate Access** ($\mu_{\text{Mod\_A}}$)

  * **Description:** Represents medium risk; the distance is a logistical hurdle but not insurmountable.
  
  * **Membership Function:** **Triangular** $\text{trimf}(x; a, b, c)$.
  
  * **Parameters:** $a=3, b=6, c=10$.

C. Fuzzy Set: **Difficult Access** ($\mu_{\text{Diff\_A}}$)

  * **Description:** Represents high PPD risk due to poor access, high travel cost/time, and high stress during labor/emergencies.
  
  * **Membership Function:** **Right-Open Trapezoidal** $\text{trapmf}(x; a, b, c, d)$.
  
  * **Parameters:** $a=8, b=15, c=50, d=50$.

In [420]:
import numpy as np
import pandas as pd
import skfuzzy as fuzz

# Define the universe of discourse (0.5 to 50 km)
MIN_DIST = 0.5
MAX_DIST = 50.0
dist_universe = np.arange(MIN_DIST, MAX_DIST + 0.5, 0.5) 

# Define the Contextual Parameters for Fuzzy Sets

# A. Easy Access (Trap): Full membership up to 2 km, 0 at 5 km
easy_a_params = [0.5, 2.0, 2.0, 5.0] 

# B. Moderate Access (Tri): Starts 3 km, Peaks 6 km, Ends 10 km
mod_a_params = [3.0, 6.0, 10.0]

# C. Difficult Access (Trap): 0 at 8 km, Full membership from 15 km
diff_a_params = [8.0, 15.0, 50.0, 50.0]

# Pre-compute the membership functions (MFs)
easy_a_mf = fuzz.trapmf(dist_universe, easy_a_params)
mod_a_mf = fuzz.trimf(dist_universe, mod_a_params)
diff_a_mf = fuzz.trapmf(dist_universe, diff_a_params)

In [421]:
# Fuzzification Function (Applied to the entire column)

def fuzzify_distance(df: pd.DataFrame, dist_universe: np.ndarray) -> pd.DataFrame:
    """Calculates the degree of membership for the entire distance_to_health_facility column."""
    
    # Ensure input data is treated as continuous/float
    input_data = df['distance_to_health_facility'].astype(float)
    
    # Apply interpolation to the entire column
    mu_easy = [
        fuzz.interp_membership(dist_universe, easy_a_mf, x)
        for x in input_data
    ]
    
    mu_mod = [
        fuzz.interp_membership(dist_universe, mod_a_mf, x)
        for x in input_data
    ]
    
    mu_diff = [
        fuzz.interp_membership(dist_universe, diff_a_mf, x)
        for x in input_data
    ]
    
    # Create the new fuzzy feature DataFrame
    return pd.DataFrame({
        'mu_distance_easy': mu_easy,
        'mu_distance_moderate': mu_mod,
        'mu_distance_difficult': mu_diff
    })

In [422]:
# Execute Fuzzification and Merge: 

fuzzy_df_dist = fuzzify_distance(df, dist_universe)
print(fuzzy_df_dist.shape)

#df = pd.concat([df, fuzzy_df_dist], axis=1)
#print(df.shape)

fuzzy_df = pd.concat([fuzzy_df, fuzzy_df_dist], axis=1)
print(fuzzy_df.shape)

(20000, 3)
(20000, 54)

----
----
-----

In [424]:
df.shape

(20000, 32)

In [425]:
df.columns

Index(['age', 'residence', 'province', 'ethnicity',
       'caste_discrimination_exposure', 'education_level', 'occupation',
       'family_type', 'wealth_index', 'monthly_household_income',
       'food_security', 'housing_quality', 'financial_stress_level', 'parity',
       'anc_visits', 'delivery_type', 'birth_complications',
       'baby_health_status', 'gestational_age', 'maternal_age_at_first_birth',
       'previous_pregnancy_loss', 'partner_support_score',
       'family_support_score', 'domestic_violence_exposure',
       'social_isolation_score', 'sleep_quality', 'stressful_life_events',
       'mental_health_awareness', 'distance_to_health_facility',
       'health_insurance', 'previous_mental_health_consultation',
       'ppd_risk_level'],
      dtype='object')

In [ ]:
fuzzy_df.shape # 18x 3= 54 features

(20000, 54)

In [427]:
fuzzy_df.head(2)

,mu_age_young,mu_age_prime,mu_age_advanced,mu_edu_low_risk,mu_edu_medium_risk,mu_edu_high_risk,mu_wealth_high_poverty,mu_wealth_medium_wealth,mu_wealth_low_poverty,mu_inc_low,...,mu_isolation_high,mu_sleep_poor,mu_sleep_moderate,mu_sleep_good,mu_stress_low,mu_stress_mod,mu_stress_high,mu_distance_easy,mu_distance_moderate,mu_distance_difficult
0,1.0,0.0,0.0,0.2,0.8,0.0,0.0,0.3,0.7,0.00000,...,0.0,0.00,0.466667,0.15,1.0,0.000000,0.0,0.420000,0.00,0.0
1,0.0,0.0,0.5,0.7,0.3,0.0,0.0,0.3,0.7,0.20932,...,0.7,0.85,0.120000,0.00,0.0,0.333333,0.0,0.056667,0.61,0.0

In [428]:
fuzzy_df.columns

Index(['mu_age_young', 'mu_age_prime', 'mu_age_advanced', 'mu_edu_low_risk',
       'mu_edu_medium_risk', 'mu_edu_high_risk', 'mu_wealth_high_poverty',
       'mu_wealth_medium_wealth', 'mu_wealth_low_poverty', 'mu_inc_low',
       'mu_inc_mod', 'mu_inc_high', 'mu_fs_high_risk', 'mu_fs_mod_risk',
       'mu_fs_low_risk', 'mu_hq_low', 'mu_hq_mod', 'mu_hq_high',
       'mu_stress_low', 'mu_stress_mod', 'mu_stress_high', 'mu_parity_low',
       'mu_parity_opt', 'mu_parity_high', 'mu_anc_inadequate',
       'mu_anc_sufficient', 'mu_anc_optimal', 'mu_ga_preterm', 'mu_ga_optimal',
       'mu_ga_late_post', 'mu_maternal_age_early', 'mu_maternal_age_optimal',
       'mu_maternal_age_advanced', 'mu_support_low', 'mu_support_mod',
       'mu_support_high', 'mu_family_inadequate', 'mu_family_moderate',
       'mu_family_strong', 'mu_dv_high_risk', 'mu_dv_mod_risk',
       'mu_dv_no_risk', 'mu_isolation_low', 'mu_isolation_mod',
       'mu_isolation_high', 'mu_sleep_poor', 'mu_sleep_moderate',
       'mu_sleep_good', 'mu_stress_low', 'mu_stress_mod', 'mu_stress_high',
       'mu_distance_easy', 'mu_distance_moderate', 'mu_distance_difficult'],
      dtype='object')

In [429]:
df_crisp_encoded.shape

(20000, 28)

In [430]:
df_crisp_encoded.head()

,province_Gandaki,province_Karnali,province_Koshi,province_Lumbini,province_Madhesh,province_Sudurpashchim,ethnicity_Hill High Caste,ethnicity_Janajati,ethnicity_Muslim,ethnicity_Terai Caste,...,mental_health_awareness_Low,mental_health_awareness_Medium,residence,caste_discrimination_exposure,family_type,birth_complications,previous_pregnancy_loss,health_insurance,previous_mental_health_consultation,ppd_risk_level
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,1,0,1,0,0,1,1,0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0,1,1,1,0,0,0,2
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0,0,1,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0,0,0,0,0,0,0,0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0,0,1,0,0,0,0,1

### **Concatenate Crisp and Fuzzy Encoded Features:**

In [ ]:
# Concatenate crisp encoded features with fuzzy features
# The target column 'ppd_risk_level' is already included in df_crisp_encoded

hybrid_df = pd.concat([df_crisp_encoded, fuzzy_df], axis=1)

In [432]:
print(f"Crisp Encoded Features Shape: {df_crisp_encoded.shape}")
print(f"Fuzzy Features Shape: {fuzzy_df.shape}")
print(f"Hybrid DataFrame Shape: {hybrid_df.shape}")

Crisp Encoded Features Shape: (20000, 28)
Fuzzy Features Shape: (20000, 54)
Hybrid DataFrame Shape: (20000, 82)

In [438]:
df_crisp_encoded.columns, df_crisp_encoded.shape

(Index(['province_Gandaki', 'province_Karnali', 'province_Koshi',
        'province_Lumbini', 'province_Madhesh', 'province_Sudurpashchim',
        'ethnicity_Hill High Caste', 'ethnicity_Janajati', 'ethnicity_Muslim',
        'ethnicity_Terai Caste', 'occupation_Clerical', 'occupation_Manual',
        'occupation_Professional/Technical/Managerial',
        'occupation_Sales/Service', 'delivery_type_Cesarean',
        'delivery_type_Normal', 'baby_health_status_Major issues',
        'baby_health_status_Minor issues', 'mental_health_awareness_Low',
        'mental_health_awareness_Medium', 'residence',
        'caste_discrimination_exposure', 'family_type', 'birth_complications',
        'previous_pregnancy_loss', 'health_insurance',
        'previous_mental_health_consultation', 'ppd_risk_level'],
       dtype='object'),
 (20000, 28))

In [433]:
# Display the first few rows of the hybrid dataframe
hybrid_df.head()

,province_Gandaki,province_Karnali,province_Koshi,province_Lumbini,province_Madhesh,province_Sudurpashchim,ethnicity_Hill High Caste,ethnicity_Janajati,ethnicity_Muslim,ethnicity_Terai Caste,...,mu_isolation_high,mu_sleep_poor,mu_sleep_moderate,mu_sleep_good,mu_stress_low,mu_stress_mod,mu_stress_high,mu_distance_easy,mu_distance_moderate,mu_distance_difficult
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.00,0.466667,0.15,1.0,0.000000,0.0,0.420000,0.000000,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.7,0.85,0.120000,0.00,0.0,0.333333,0.0,0.056667,0.610000,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.2,0.00,0.733333,0.00,1.0,0.000000,0.0,0.000000,0.000000,1.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.15,0.680000,0.00,1.0,0.000000,0.0,0.000000,0.823333,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.3,0.30,0.560000,0.00,0.0,1.000000,0.0,0.940000,0.000000,0.0

In [442]:
fuzzy_df.columns, fuzzy_df.shape

(Index(['mu_age_young', 'mu_age_prime', 'mu_age_advanced', 'mu_edu_low_risk',
        'mu_edu_medium_risk', 'mu_edu_high_risk', 'mu_wealth_high_poverty',
        'mu_wealth_medium_wealth', 'mu_wealth_low_poverty', 'mu_inc_low',
        'mu_inc_mod', 'mu_inc_high', 'mu_fs_high_risk', 'mu_fs_mod_risk',
        'mu_fs_low_risk', 'mu_hq_low', 'mu_hq_mod', 'mu_hq_high',
        'mu_stress_low', 'mu_stress_mod', 'mu_stress_high', 'mu_parity_low',
        'mu_parity_opt', 'mu_parity_high', 'mu_anc_inadequate',
        'mu_anc_sufficient', 'mu_anc_optimal', 'mu_ga_preterm', 'mu_ga_optimal',
        'mu_ga_late_post', 'mu_maternal_age_early', 'mu_maternal_age_optimal',
        'mu_maternal_age_advanced', 'mu_support_low', 'mu_support_mod',
        'mu_support_high', 'mu_family_inadequate', 'mu_family_moderate',
        'mu_family_strong', 'mu_dv_high_risk', 'mu_dv_mod_risk',
        'mu_dv_no_risk', 'mu_isolation_low', 'mu_isolation_mod',
        'mu_isolation_high', 'mu_sleep_poor', 'mu_sleep_moderate',
        'mu_sleep_good', 'mu_stress_low', 'mu_stress_mod', 'mu_stress_high',
        'mu_distance_easy', 'mu_distance_moderate', 'mu_distance_difficult'],
       dtype='object'),
 (20000, 54))

In [434]:
# Display all columns in the hybrid dataframe
print("Total number of columns:", len(hybrid_df.columns))
print("\nAll columns in hybrid_df:")
hybrid_df.columns.tolist()

Total number of columns: 82

All columns in hybrid_df:

['province_Gandaki',
 'province_Karnali',
 'province_Koshi',
 'province_Lumbini',
 'province_Madhesh',
 'province_Sudurpashchim',
 'ethnicity_Hill High Caste',
 'ethnicity_Janajati',
 'ethnicity_Muslim',
 'ethnicity_Terai Caste',
 'occupation_Clerical',
 'occupation_Manual',
 'occupation_Professional/Technical/Managerial',
 'occupation_Sales/Service',
 'delivery_type_Cesarean',
 'delivery_type_Normal',
 'baby_health_status_Major issues',
 'baby_health_status_Minor issues',
 'mental_health_awareness_Low',
 'mental_health_awareness_Medium',
 'residence',
 'caste_discrimination_exposure',
 'family_type',
 'birth_complications',
 'previous_pregnancy_loss',
 'health_insurance',
 'previous_mental_health_consultation',
 'ppd_risk_level',
 'mu_age_young',
 'mu_age_prime',
 'mu_age_advanced',
 'mu_edu_low_risk',
 'mu_edu_medium_risk',
 'mu_edu_high_risk',
 'mu_wealth_high_poverty',
 'mu_wealth_medium_wealth',
 'mu_wealth_low_poverty',
 'mu_inc_low',
 'mu_inc_mod',
 'mu_inc_high',
 'mu_fs_high_risk',
 'mu_fs_mod_risk',
 'mu_fs_low_risk',
 'mu_hq_low',
 'mu_hq_mod',
 'mu_hq_high',
 'mu_stress_low',
 'mu_stress_mod',
 'mu_stress_high',
 'mu_parity_low',
 'mu_parity_opt',
 'mu_parity_high',
 'mu_anc_inadequate',
 'mu_anc_sufficient',
 'mu_anc_optimal',
 'mu_ga_preterm',
 'mu_ga_optimal',
 'mu_ga_late_post',
 'mu_maternal_age_early',
 'mu_maternal_age_optimal',
 'mu_maternal_age_advanced',
 'mu_support_low',
 'mu_support_mod',
 'mu_support_high',
 'mu_family_inadequate',
 'mu_family_moderate',
 'mu_family_strong',
 'mu_dv_high_risk',
 'mu_dv_mod_risk',
 'mu_dv_no_risk',
 'mu_isolation_low',
 'mu_isolation_mod',
 'mu_isolation_high',
 'mu_sleep_poor',
 'mu_sleep_moderate',
 'mu_sleep_good',
 'mu_stress_low',
 'mu_stress_mod',
 'mu_stress_high',
 'mu_distance_easy',
 'mu_distance_moderate',
 'mu_distance_difficult']

In [435]:
# Verify that the target column 'ppd_risk_level' is present
print("Target column 'ppd_risk_level' present:", 'ppd_risk_level' in hybrid_df.columns)
print("\nTarget column distribution:")
hybrid_df['ppd_risk_level'].value_counts()

Target column 'ppd_risk_level' present: True

Target column distribution:

ppd_risk_level
0    8149
1    8092
2    3759
Name: count, dtype: int64

In [436]:
# Save hybrid df as a csv file:
hybrid_df.to_csv('hybrid_matrix.csv', index=False)